### ISSUE TITLE
User form. Data associated with the territory table

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#102]
How information is added to this table?

**Comment by gon-nexus** [comment]
For each different territory added to the permission table, a line is created in the new table.

You'll see that there are more permissions than territories at first, that's for test data, it's not a bug

**Comment by IDEmenorca** [comment]
Where does this list com from?

![imagen](https://user-images.githubusercontent.com/26217441/140898740-ad2e86e6-eee1-4486-9dc7-2d085277b6cb.png)

**Comment by fjlopez** [comment]
The origin of the list it the code list `userPosition.type` which are user position types used in the Diputació de Barcelona. The labels of this code list are available in EN and CA.

**Comment by IDEmenorca** [comment]
ok, 

In this usecase (image below) is it normal that the territory' Provincia de Barcelona don't appear in the 'dades associades al territori' table? Is it because the 'Provincia de barcelona' is parent layer of St martí de Cencelles?
![imagen](https://user-images.githubusercontent.com/26217441/145959302-841a59a3-4113-4bd2-9023-cd7a579b5827.png)
