### ISSUE TITLE
Change the behavior of the "Elimina" button 

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#11]
The “Elimina” button is always clickable, despite no items are selected in the grid. When clicking on this button without items selected the behavior is: sometimes the confirmation pop-up wrongly appears and sometimes the button does nothing.

Maybe a better behavior would be to show this button in grey (or similar) and make it not clickable when there are no items selected to be erased.

**Comment by lucenasj** [comment]
Can you validate this button functionality proposal?

**Comment by montsemarco** [comment]
I would prefer the button always present and deactivated instead of hidden. I think it would be better to leave it in standby to ask the opinion from the other participants in the next meeting.

**Comment by lucenasj** [comment]
this is the other option:

![image](https://user-images.githubusercontent.com/72931574/107505751-714f6c00-6b9d-11eb-8dce-32f1a6159a7f.png)

**Comment by montsemarco** [comment]
I think that this is a better option. For instance, in the screen above, hidding and showing the "Elimina" button would make the 'Cerca' box to change the position in the layout. 

Besides, if the button is always visible, the user is aware that there is a way to remove an element from the list and makes the application more usable, from my point of view.

**Comment by montsemarco** [comment]
For consistency, I guess that the same behavior should be applied to the ‘Export’ and ‘Duplicate’ actions

![imagen](https://user-images.githubusercontent.com/1905272/116246020-dd3b7c80-a769-11eb-824a-7638bf9b1d82.png)
