### ISSUE TITLE
Permission over the layers form.

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#118]
Related to issue #99 

Type not listed in the general selection table. 
![imagen](https://user-images.githubusercontent.com/26217441/140896192-716e56ff-ae78-446c-a0e8-31d403440b3f.png)

And still the appears the background map option in the type combo.

![imagen](https://user-images.githubusercontent.com/26217441/140896496-76791b63-fc89-41a6-bfb6-57fe8113d191.png)

**Comment by gon-nexus** [comment]
Waiting https://github.com/sitmun/sitmun-backend-core/issues/131
