### ISSUE TITLE
Layer form. Load attributes for spatial selecction

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#119]
When loading attributes for spatial selection an error is obtained....
![imagen](https://user-images.githubusercontent.com/26217441/140904670-2a4e67ff-a01d-4c9b-be60-555f9d15e4f8.png)

Provably I've done something wrong as I'm pretty sure I've already tested this funcionality...

**Comment by gon-nexus** [comment]
Can you tell me what URL has the service you used in the test? @IDEmenorca

**Comment by lucenasj** [comment]
Can you tell us what URL has the service you used in the test? @IDEmenorca

**Comment by IDEmenorca** [comment]
I was using https://ide.cime.es/geoserver/ambiental/wfs/?service=wfs&request=getcapabilities 

But it is working now... Have you changed anything or may I have done something wrong?

Anycase I'm clossing the issue.
