### ISSUE TITLE
BACKGROUND - New

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#12]
I can update an existing Background and change its Group to null. But when I create a new background with Group=null, I get the error "undefined. undefined".

**Comment by lucenasj** [comment]
Backend require cartographyGroup, but in sitmun2 can be null, I have reported to backend developers this issues
{
  "errors" : [ {
    "entity" : "Background",
    "property" : "cartographyGroup",
    "invalidValue" : null,
    "message" : "must not be null"
  } ]
}

**Comment by fjlopez** [comment]
Fix in progress in https://github.com/sitmun/sitmun-backend-core/issues/67

**Comment by fjlopez** [comment]
@codinachssm, you can check this feature again when @lucenasj confirms my fix in sitmun/sitmun-backend-core#67

**Comment by lucenasj** [comment]
fixed and closed

**Comment by codinachssm** [comment]
It seems I can create a new one with group=null but I cannot update anyone to group=null.

**Comment by lucenasj** [comment]
can you try again?

**Comment by codinachssm** [comment]
Fixed! Thanks!
