### ISSUE TITLE
Use label instead of code in Tipo in Terriotory list

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#120]
Issue found in https://github.com/sitmun/sitmun-admin-app/issues/70#issuecomment-968078837_

![image](https://user-images.githubusercontent.com/3294927/141647946-7977dbfb-66c3-4ea4-a2ac-301866cc5e8e.png)

`Tipo` should be the label of the type of territory (e.g.  `Provincia` instead of `8` and `Consell Comarcal` instead of `2`)

**Comment by lucenasj** [comment]
![image](https://user-images.githubusercontent.com/72931574/145996932-4fa7aeb3-c5b2-4963-94dd-acd98562139b.png)
