### ISSUE TITLE
Tasks-Query-Edit: Access type is null

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#122]
Some elements have the field "Access type" null although it is mandatory. Is it because the test data is not complete, or is it due to an application error?
Example:
![image](https://user-images.githubusercontent.com/38311286/142839421-9cd8f5f1-22b5-41b0-bee4-19e0a55a7a2d.png)

**Comment by gon-nexus** [comment]
This is because of test data, the app doesn't let you create a query-task without access type

**Comment by codinachssm** [comment]
OK. But even when I edit an element and enter a value for its access type and save it, it remains null in the grid (although it has a value when I edit it again).

**Comment by gon-nexus** [comment]
Yes, I detected the error when I checked the issue, the next update will fix it!

**Comment by codinachssm** [comment]
OK
