### ISSUE TITLE
Tasks-Query-Edit, Tasks-More information-Edit & Tasks-Locator-Edit: Task parameter (SQL Type case)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#123]
a) How can I represent the Key parameter within the SQL command in the general data panel?
b) Is it possible to edit (modify) an existing Task parameter item in the Task parameter panel?
c) Is it possible to include the Label column in the Task parameter panel?

**Comment by codinachssm** [comment]
a) OK
b) I can modify some fields (not the Label) but the form is not useful for the Value field. For example, it can be a very long SQL statement. Example: 
![image](https://user-images.githubusercontent.com/38311286/145953015-607d48d6-f7f6-4c63-862a-47891fcc775f.png)
c); I can't see the Label, so I can't edit it.

**Comment by codinachssm** [comment]
b) The length of the Value task parameter seems smaller than in STM2 and it's not possible to include RETURN inside the SQL code

**Comment by gon-nexus** [comment]
The behavior of this component is the same as the other textarea in the application:
![image](https://user-images.githubusercontent.com/73172087/147445712-e84a5c7f-dac0-4e19-a52d-9adbe3209443.png)
Si fas click en aquest botó, pots fer el component tant gran com vulguis
![image](https://user-images.githubusercontent.com/73172087/147445828-7461f1db-1120-4452-b148-48e80a9909ad.png)

On the other hand, to add a return, you must keep shift key pressed when you click the intro key:
![image](https://user-images.githubusercontent.com/73172087/147445923-9194fcd7-3eea-4968-8afc-59738dcbeac5.png)

**Comment by fjlopez** [comment]
> b) The length of the Value task parameter seems smaller than in STM2 and it's not possible to include RETURN inside the SQL code

It does not seem to be something related with the backend. 
- The backend supports up to 4000 characters stored in the `value` property of `TaskParameter`.
- The backend does not sanitise its content (e.g. remove new lines).

**Comment by codinachssm** [comment]
b) OK. But would it possible to move the ORDER column before the VALUE in all Task-Edit-Parameters where VALUE can be a SQL command? Otherwise, when the value is quite long the user cannot see the order column easily. (See the example below)

![image](https://user-images.githubusercontent.com/38311286/149741645-3ead7b11-7397-43f4-8e99-1e79626036fc.png)
