### ISSUE TITLE
Main pages - Number of rows displayed

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#127]
How can I assign the number of rows to display on the main pages? (similar to what we do with the grid panels).
I can always see 12 rows but it is not enough and there much more space to be used.
Example:
![image](https://user-images.githubusercontent.com/38311286/143822772-5fde2f57-ccec-4f15-a656-0d4321a67bd5.png)

**Comment by gon-nexus** [comment]
This was modified without us realizing when we changed the numbers of showing rows from the other tables, now it should be correct.
