### ISSUE TITLE
Dashboard - Takes too long

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#130]
Could you confirm that the queries are pre-calculated? They take too long to run.

**Comment by fjlopez** [comment]
Yes, queries are pre-calculated in the backend.  The request to the `/info` endpoint does not trigger computation. 

The infrastructure is as follows: 
- The metrics implements the interface [DashboardMetricsContributor](https://github.com/sitmun/sitmun-backend-core/blob/master/src/main/java/org/sitmun/plugin/core/dashboard/DashboardMetricsContributor.java) that computes the value.
- [ScheduleTasks.java](https://github.com/sitmun/sitmun-backend-core/blob/44c48ea9c9fbca6939c23912b1a72f89d9de3f4e/src/main/java/org/sitmun/plugin/core/dashboard/ScheduledTasks.java) runs jobs each 60 secs (configurable) to pre-compute them.
- [DashboardInfoContributor](https://github.com/sitmun/sitmun-backend-core/blob/master/src/main/java/org/sitmun/plugin/core/dashboard/DashboardInfoContributor.java) publishes the pre-computed data.

**Comment by codinachssm** [comment]
OK, thanks.
