### ISSUE TITLE
Uses of /api/account 

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#132]
I am reviewing the backend code for removing obsolete code. I think that the endpoint `/api/account` is not used by the administrator client. @lucenasj or @gon-nexus, can you confirm if it is used, and if so, which are its uses?

**Comment by gon-nexus** [comment]
Yes, we use this endpoint for user authentication.

**Comment by fjlopez** [comment]
I think you refer to `/api/authenticate` (send user and password and return the jwt token). Account is an endpoint that allows to read and modify data of the logged user.

**Comment by fjlopez** [comment]
@gon-nexus can you confirm that the only use of `/api/account` is to test if the JWT token is valid?

**Comment by gon-nexus** [comment]
Yes, i confirm it
