### ISSUE TITLE
No se pueden crear parámetros de tarea

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#134]
El control `clau` es un combo desplegable vacío pero obligatorio. No es posible introducir un nuevo parámetro con esta configuración.

<img width="767" alt="Captura de Pantalla 2022-03-30 a las 18 10 13" src="https://user-images.githubusercontent.com/3294927/160881445-f5018a37-4b3d-4a91-92d7-5fe8ae2f3c1e.png">

**Comment by gon-nexus** [comment]
The 'key' selector is based on the form's SQL field, as you requested and which is explained in the user manual:
![image](https://user-images.githubusercontent.com/73172087/160991656-a332bf99-1b3e-485a-beb4-627a4d0ad3cf.png)

**Comment by fjlopez** [comment]
Ok! Thanks. I forget this detail!
