### ISSUE TITLE
Error on assigning territory to an existing role

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-admin-app#136]
**Describe the bug**
Error on assigning territory to an existing role. A message appear when saving

**To Reproduce**
1. Go to 'Role' -> 'Combinació de territori i usuaris' 
2. Click on 'Afegeix'
3. Check user 2 (public) and territory 4 (Menorca)
4. Click on 'Afegeix'
5. Click 'Desa' button
6. See error

**Expected behavior**
It is expected to assign new territory to existing role

**Screenshots**
![err1](https://github.com/sitmun/sitmun-admin-app/assets/6534787/9aaa8402-c47b-42d9-bad8-8c4a5b11a195)

**Comment by fjlopez** [comment]
Nested exception identified:

<img width="1213" alt="image" src="https://github.com/sitmun/sitmun-admin-app/assets/3294927/953b7aee-1ead-4465-96ec-85f3ea297297">

**Comment by fjlopez** [comment]
Fixed in https://github.com/sitmun/sitmun-backend-core/commit/75d1d5e1af3fc2537a64645af4215e6b7a427095. It was an error in the initial data.
