### ISSUE TITLE
Url must be optional for internal applications

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#138]
**Describe the bug**
When a new application is created, the field Url must be mandatory only for external applications.

**To Reproduce**

- Go to 'Aplicació'.
- Check app 3, which is an internal app. and press 'Duplicate button'.
- On the new form, press save button.
- The new app cannot be saved because the field Url must be filled.

**Expected behavior**
The internal application can be saved because the field Url should be optional for internal applications.

**Screenshots**
![err4](https://github.com/sitmun/sitmun-admin-app/assets/6534787/27e93c02-5aca-4e84-a0f0-7f5da38a3990)

**Additional comments**
Behavior in the backend updated:  the backing field of the field Url (`jspTemplate`) is not mandatory since https://github.com/sitmun/sitmun-backend-core/commit/54f8bd259f3dfee280b6abb90a7b6b89b1c08374

**Comment by fjlopez** [comment]
**Solution**

- [ ] *change*: the field Url is optional
- [ ] *new feature*: when type is internal, the field Url is mandatory

**Comment by silmeUsil0001** [comment]
When a new application is created, the field Url is not mandatory for internal applications.

![image](https://github.com/user-attachments/assets/55af34b9-300d-4367-aebf-d13a13e7e054)
