### ISSUE TITLE
It is not allowed to implement WMTS service

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-admin-app#139]
**Describe the bug**
It is not allowed to implement WMTS service? The WMTS option for a new service is not displayed in the combo selector service type. There are only these options: AIMS, FME, TC,, WFS and WMS. 

**To Reproduce**
1. Go to 'Servei'-> ' Nou'
2. Click on 'Tipus combo'
![err5](https://github.com/sitmun/sitmun-admin-app/assets/6534787/cf60471b-d73f-41d3-bc9b-b9213b025970)

3.- If WMS option is selected, an error ocurred when trying to obtain data from the service
![err6](https://github.com/sitmun/sitmun-admin-app/assets/6534787/46702aa8-55aa-4f8a-ac76-78e09d08b538)

**Expected behavior**
A WMTS option to select
**Screenshots**

**Comment by fjlopez** [comment]
Fixed.
