### ISSUE TITLE
SITMUN3 - Edition panels

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#14]
1. By which attribute are the detailed rows ordered?
2. The working texts are: "pending creation" and "deleted". But for search purpose perhaps it wolud be easier to homogenize them (for example, to add "pending" to all texts)

**Comment by codinachssm** [comment]
1. Still have the question, for example in CAPES-EDITA.Territori: I cann't find out by which columned it is ordered by.
2. OK

**Comment by gon-nexus** [comment]
If the table has the field  "order" it will be sorted by this one, if the table has not the field,  it is not sorted by any particular column, but if you click on the column name, the table will be sorted by the clicked column

**Comment by codinachssm** [comment]
In SITMUN2, in this case of CAPES-EDITA.Territori, the elements are always ordered by the TERRITORY.NAME column. It's much easier for the user. Please, could you add this sort?

**Comment by gon-nexus** [comment]
Of course! If you need any other sort tell me!

**Comment by codinachssm** [comment]
Ok. In fact, it would be much easier if it is sorted like in SITMUN2:
- If an "ORDER" column existts, then this is the column to be used.
- If not, then de NAME column should be used.
Exceptions: 
- Users --> USE_USER
- User - Permissions --> Territory.name
- User - Data associated to a territory --> Territory.name

**Comment by codinachssm** [comment]
Layer Edition panel --> Nodes
As all the node names are equal or very similar, is it possible to add a second field to be ordered by? It would be much easier for users if rows are ordered by NodeName (first) and TreeName (second), not only by NodeName.

Service Edition panel --> Configuration parameters
It seems it is ordered by ID. Could it be ordered by Request (first) and Parameter (second)?

Thanks!!
