### ISSUE TITLE
It is not allowed to add parameters in a Service excpet WMS parameters

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-admin-app#141]
**Describe the bug**
It is not allowed to add parameters in a Service excpet WMS parameters. In a WMTS service a "matrixSet" is requiered, but it is not possible to add it, only INFO, OLPARAM and WMS type parameters are allowed

**To Reproduce**
1. Go to 'Serveis'
2. Click on '154' and edit service
3. Scroll down to 'Paràmetres de configuració del servei' and push 'Nou'. 

**Expected behavior**
A combobox with other options should be available. Or a textbox to introduce any value

**Screenshots**
![err10](https://github.com/sitmun/sitmun-admin-app/assets/6534787/f0112588-8f32-4fd8-a84c-f93c15cd0d07)

**Comment by fjlopez** [comment]
Fixed, see #143  but I discovered a bug in the admin client. The combo list should show code lists labels (e.g. "WMTS Options") rather than codes (e.g. "WMTS").

**Comment by fjlopez** [comment]
I have created https://github.com/sitmun/sitmun-admin-app/issues/144 for reporting the new bug.
