### ISSUE TITLE
Why can't add a new base map layer?

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-admin-app#143]
**Describe the bug**
I want to add a new base map layer to an application and I can't understand what I'm doing wrong, because it never appears on the basemap area

**To Reproduce**
1.- A new WMTS service is duplicated from Service number 1. The new service is the 153
2.- A new base WMTS layer is duplicated from layer number 1. The new layer is 1305
3.- Layer nmber 1305 is added to "capes de fons"  number 8
4.- I think it has all privileges (role, territory, applications) set properly, but it doesn't appear in the base map area on the public viewer...

![err13](https://github.com/sitmun/sitmun-admin-app/assets/6534787/8e375b85-ac4c-4aaa-b56a-757680ce8df7)

**Comment by fjlopez** [comment]
I think it is fixed:

- I added added WMTS to `stm_CODELIST`
- As WMTS property,  the property `matrixSet` with value `EPSG:25831``

@silmeUsil0001 validate it, please

**Comment by fjlopez** [comment]
This issue is a viewer issue. See https://github.com/sitmun/sitmun-viewer-app/issues/39
