### ISSUE TITLE
Folder name in a Tree can't be changed

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#148]
**Describe the bug**
Changing the name of a folder inside a tree doesn't work and gives an error.

**To Reproduce**
1. Go to 'trees' menu and edit an existing tree
2. Click on expand nodes and folders
3. Edit a folder, change its name
4. Apply changes
5. Save changes
6. See error

**Screenshots**
![image](https://github.com/sitmun/sitmun-admin-app/assets/26217441/109cd08e-b162-45a6-a587-9503eb526a6f)

![image](https://github.com/sitmun/sitmun-admin-app/assets/26217441/f863987e-e223-475b-a069-5fdf0d9546b4)

**Comment by fjlopez** [comment]
Please, complete the description of the issue.

**Comment by fjlopez** [comment]
Seems fixed
