### ISSUE TITLE
Improve task 'localitzador'

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#149]
**Describe the bug**
It looks like the task 'Localitzador' is not defined properly. It should allow to configure the parameters needed by the search control form API-SITNA.

**To Reproduce**
1. Go to tasks
2. Click on Localitzador
4. See parameters

**Screenshots**
Main params
![image](https://github.com/sitmun/sitmun-admin-app/assets/26217441/e287e0b5-3d8c-4453-bec7-265c11020d03)

Task specific parameters
![image](https://github.com/sitmun/sitmun-admin-app/assets/26217441/2e393365-a34c-466f-98c9-8b604284fa81)

**Comment by fjlopez** [comment]
Please, complete the description of the task.

**Comment by fjlopez** [comment]
@mvinent could you review this request and complete the description?

**Comment by mvinent** [comment]
The task should allow to configure the parameters needed by the API-SITNA and then show them in the JSON returned by the API in a way that the API-SITNA can interpret them.

This is an example of the parameters that the 'search' control needs to work properly:
![image](https://github.com/user-attachments/assets/cde0857f-6da2-455e-b943-a5ac73025d54)
