### ISSUE TITLE
SITMUN3 - Edition panels height

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#15]
The detailed panels following the edition form should be possible to be enlarged in some way. For example, the Parameters panel for the IG (cartography), in some cases we have more than 50 rows. As we need to assign an order number to each row, it is impossible to do it by seeing only 4 rows at once. The same solution should be applied to all the detailed panels for homogenization.

**Comment by lucenasj** [comment]
![image](https://user-images.githubusercontent.com/72931574/107970839-f37ecc80-6fb1-11eb-91de-81a2f04436a2.png)

**Comment by codinachssm** [comment]
In the case of the "Cartography.Parameters", we need to see as much panel as possible because we must order each row following the user instructions. In sitmun2 we can see 20 rows at once, withoug scrolling. And there's a scroll to see even more, if necessary. There are cartographies with 50 and 60 rows of parameters in our production platform. Here you can see an example of 30 rows: "ACE1M - Activitats per sector (intern)".
In general, maybe it shlould be possible to enlarge the panel.
