### ISSUE TITLE
JSON sent not matching admin's tree structure

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-admin-app#151]
**Describe the bug**
When adding multiple layers in a single node, each one is sent in a separate node.

**To Reproduce**
1. Go to admin
2. Add diffenrent layers on a single node
3. Go to Viewer App
4. Open layers tree
5. See error

**Expected behavior**
Layers should hang from a single node if specified in the admin.

**Screenshots**
Tree configuration in the admin.
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/c04876fc-a34e-4641-9324-39830f605637)

Node from which layers should hang
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/848233c8-b56a-47b7-8ada-72d85aebfb4b)

Single node with a single layer
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/3f4a6526-7a83-4818-990a-d303bb86dc00)

End layer
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/2a6a2d7e-10e7-4527-bba7-4ecda7dd77e0)

Tree as seen in the Viewer App
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/f12e90bc-6a0c-4645-9154-81f61d425e1e)

**Comment by fjlopez** [comment]
Could you add screenshots of Me03 JSON nodes?

**Comment by mvinent** [comment]
> Could you add screenshots of Me03 JSON nodes?

Issue updated to match screenshots

**Comment by fjlopez** [comment]
This is an issue of the sitmun-viewer-app. Leaf nodes (nodes linked  to resources) are interpreted as folder nodes (nodes with children) and resources (layers) are interpreted as leaf nodes. This is wrong. The tree map should render nodes, and how the node is rendered depends on being a folder (nodes with children) or, for example, layer (nodes with a resource that points to a layer). 

@mvinent, 
- [ ] create a new issue in sitmun-viewer-app with all the details of the issue
- [ ] mention this one as source
- [ ] label this one as duplicated and 
- [ ] close it.

**Comment by fjlopez** [comment]
@mvinent, can I close this bug?

**Comment by mvinent** [comment]
Yes, I think it can be closed
