### ISSUE TITLE
Service form. Authentication method should have "None" value as default

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#152]
AUTHENTICATION METHOD Field: As it is mandatory, it would be easier if it takes the NONE default value, as it is the most common case.
![image](https://github.com/sitmun/sitmun-admin-app/assets/38311286/ce4d231d-5239-4609-8821-a3882afcd544)

**Comment by fjlopez** [comment]
Duplicated of bug https://github.com/sitmun/sitmun-admin-app/issues/198
