### ISSUE TITLE
Application form. The location map can't be changed when editing an existing application

### ISSUE THREAD

**Issue by rbejar** [sitmun/sitmun-admin-app#159]
**Describe the bug**
Modifying the location map in an existing application fails.
It also fails to report the error: it shows "items updated successfully".

**To Reproduce**
1. Go to <https://sitmun.github.io/admin-app/#/dashboard>
2. Login.
3. Choose `Application` on the left side.
4. Click on the pencil icon (edit) the application with id 15.
5. In the Location Map drop-down choose "Mapa de situació"
6. Click on the save button.

**Expected behavior**
It should update the location map of the application 15.
But it does not. It briefly shows a red box, but it ends up showing "items updated successfully". However, if you return and edit the application 15 agian, the location map has not been changed.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser: Vivaldi. 
 - Version: Latest.

**Comment by fjlopez** [comment]
The client makes a wrong request to `/api/applications/15/situationMap%7B?projection`

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-admin-app/commit/31f1ac562eec975afa3ca040f7aed909fae0a5eb).

**Comment by fjlopez** [comment]
This commit is not yet merged in Updates. See my comment in #243

**Comment by mvinent** [comment]
Merge validated c58f33c702660cededfc45a5f929ae454500c6dc
