### ISSUE TITLE
TERRITORY - "Codi"

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#16]
The "Codi" column on the Territtory page should show the "0" on its left. Maybe it is processed like a Number type instead of a String type?

**Comment by lucenasj** [comment]
![image](https://user-images.githubusercontent.com/72931574/109128943-57428b80-7750-11eb-9bcf-cfa51e8b2ffa.png)

**Comment by fjlopez** [comment]
`code` is a `String` type in both the API and in the database (`TER_CODMUN`). 

```java
  /**
   * Geographic code.
   */
  @Column(name = "TER_CODMUN", length = IDENTIFIER)
  @NotBlank
  private String code;
```

**Comment by fjlopez** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/77 updates test data and provides 0 padded data for municipalities.
