### ISSUE TITLE
Review labels for "Layers-Edit: Trees and Nodes containing the layer"

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#160]
Correct column headings for the Node and Tree columns (for CA / ES / EN):

- For "Nodes" column - old: Name 1, new: Node / Nodo / Node

- For "Trees" column - old: Tree name 2, new: Arbre / Árbol / Tree

**Comment by fjlopez** [comment]
@codinachssm, this is not a translation issue, it is a feature of AG Grid. That table has [Multi Column Sorting](https://ag-grid.com/javascript-data-grid/row-sorting/#multi-column-sorting) enabled by default for the columns `name` and `treeName`. See below:

https://github.com/sitmun/sitmun-admin-app/blob/3cccb3d5780e43caa1e22e0d0951c2a83ab411f3/src/app/components/layers/layers-form/layers-form.component.html#L493-L497

When AG Grid does a [Multi Column Sorting](https://ag-grid.com/javascript-data-grid/row-sorting/#multi-column-sorting), it adds numbers to show how the sort order is applied. 

<img width="994" alt="image" src="https://github.com/sitmun/sitmun-admin-app/assets/3294927/279627eb-419b-4256-92e9-b6567c19bcfe">

The default action for multiple column sorting is for the user to hold down ⇧ Shift while clicking the column header. For example, in this table:
<img width="843" alt="image" src="https://github.com/sitmun/sitmun-admin-app/assets/3294927/7bf76677-9f88-4cd9-891d-b9f69a3dc9b7">

We can do a multiple column sorting: 
<img width="843" alt="image" src="https://github.com/sitmun/sitmun-admin-app/assets/3294927/2b1bb238-517e-4698-a2b6-6aeba5706efa">

It is possible to hide these numbers for good by updating the CSS. 

```css
.ag-header-cell-label .ag-header-icon.ag-sort-order {
  display: none
}
```
However, this could be confusing for the user.
