### ISSUE TITLE
Update frontend-core to Angular v10

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#166]
I'm currently updating frontend-core to Angular v10. This will include the following tests and changes:

- Test of symbolic link in sitmun-stack.
- Upload of v7 and testing.
- Upload of v8 and testing.
- Upload of v9 and testing.
- Upload of v10 and testing.

I'll keep uploading comments on the progress and problems of the process.

**Comment by albertcoro** [comment]
Actualización hasta v10 funciona, pero con errores en algunas peticiones al back.

**Comment by fjlopez** [comment]
Añade la lista de errores de peticiones al back para poder revisarlas.

**Comment by albertcoro** [comment]
El error que nos encontramos es que las peticiones se envian al localhost:8080. Captura de pantalla de peticiones:
![image](https://github.com/sitmun/sitmun-admin-app/assets/38464645/a05aacb8-3fa0-4cce-84b7-fa1d18f7c3de)
Incluso con la configuración de test o producción parece que siempre se redirigen a localhost. Captura de pantalla del archivo .env:
![image](https://github.com/sitmun/sitmun-admin-app/assets/38464645/700879fa-2ea8-440e-92b0-b6449516ad75)

**Comment by fjlopez** [comment]
¿Por qué el servicio está en el puerto 8080 en lugar del 9000? Si has usado el entorno para desarrollo local de [sitmun-application-stack](https://github.com/sitmun/sitmun-application-stack/), este está configurado para que haya un frontend con Nginx en el puerto 9000 que recibe las peticiones y las redirige internamente a un servicio backend. El administrador no hace una petición directa al backend. Si se quiere hacer esa petición directa por algún motivo, como se puede ver en el [docker-compose.yml](https://github.com/sitmun/sitmun-application-stack/blob/main/docker-compose.yml), el backend está en el puerto 9001.

**Comment by albertcoro** [comment]
Estoy usando el entorno de desarrollo local de sitmun-application-stack y tengo problemas con las peticiones. Ya que algunas peticiones funcionan correctamente y otras no. He vuelto a clonar sitmun-applicaiton-stack directamente de Github y estas peticiones no funcionan.

**Comment by albertcoro** [comment]
Existe alguna configuración extra del sitmun-application-stack, que se debe tener en cuenta para que funcionen las peticiones?

**Comment by fjlopez** [comment]
Parent issue: #164

**Comment by fjlopez** [comment]
No hay que hacer ninguna configuración adicional. Mañana revisamos qué ha podido pasar. 

Mientras tanto he creado esta rama <https://github.com/sitmun/sitmun-application-stack/tree/feature-4> que está alineada a tu rama `Updates` y que ya ha eliminado las referencias a `GITHUB_TOKEN` y a los ficheros que estaban en `dist`. Usa el código que se ha subido en #167 #168 y #169 y accede a los servicios por donde se esperaba.

**Comment by fjlopez** [comment]
@albertcoro con https://github.com/sitmun/sitmun-application-stack/commit/87650482b6d9479ee4130255a899b37f750a3768 el problema debería estar resuelto. Se han añadido los headers que faltaban en el nginx y se ha habilitado su soporte en el lado del backend. He creado una rama en el backend https://github.com/sitmun/sitmun-backend-core/tree/app-stack-feature-4 que estará también alineada a tu rama `Updates`. 

Para tener todo actualizado y que así despareciera el problema de las peticiones a localhost:8080 habría que ejecutar:

```bash
git pull --recurse-submodules
docker-compose build --no-cache
docker compose up -d
```

Confirma si el cambio resuelve el problema detectado.

**Comment by albertcoro** [comment]
@fjlopez muchas gracias, ya funcionan las request al backend
