### ISSUE TITLE
Moved frontend-core and frontend-gui into sitmun-admin-app

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#170]
Proceso para mover ambos core y gui dentro de sitmun-admin-app como si fueran componentes.
Localización:
 - Core: /src/frontend-core
 - Gui: /src/frontend-gui

**Comment by albertcoro** [comment]
Ya esta testeado y funcionando.
Los canvios se han aplicado en sitmun-admin-app

**Comment by fjlopez** [comment]
Parent issue: #164
