### ISSUE TITLE
Update admin-app to Angular 12

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#173]

**Comment by albertcoro** [comment]
@fjlopez existe un error de una request, reproducible en las siguientes branchs:
 - Sitmun-application-stack: feature-4
 - Sitmun-admin-app: Updates
 - Sitmun-backend-core: app-stack-feature-4
 - Otros: main
 
Acciones para reproducir el error:
 - Desde sitmun-application-stack ejecutaremos `docker compose up`
 - En el Menu Lateral -> Tasques -> Bàsiques -> 33 (Por ejemplo)
 - Si visualizamos las request Network, podemos ver que:
   - http://localhost:9000/backend/api/tasks/33/availabilities?projection=view -> funciona correctamente
   - http://localhost:9000/backend/api/tasks/33/cartography?projection=view -> devuleve 404 not found

**Comment by albertcoro** [comment]
Voy a abrir una nueva issue para este error de request

**Comment by fjlopez** [comment]
## Comportamiento de las Relaciones 0..1 en Spring Data Rest

No es un error, es una característica de Spring Data Rest. La relación entre Tarea y Cartografía es 0..1 y se identifica con `api/tasks/{id-tarea}/cartography/`. Si no hay una cartografía asociada a la tarea, se devuelve una respuesta 404, y si hay cartografía, se devuelve una respuesta 200 con el JSON que describe la tarea.

### Acciones para Validar el Comportamiento

1. En el Menu Lateral -> Tasques -> Bàsiques -> 33:
   - Vemos que el campo Cartografia no tiene valor. Esto se debe a que `http://localhost:9000/backend/api/tasks/33/cartography?projection=view` devuelve 404 Not Found.
   
2. Pulsamos sobre el botón + junto a Cartografía y se abre un modal para la selección de la cartografía.

3. En el modal, seleccionamos cartografía con ID 4393.

4. Pulsamos Afegeix y cerramos el modal.

5. Pulsamos Desa:
   - Vemos que entre las operaciones que se realizan hay un PUT a `http://localhost:9000/backend/api/tasks/33/cartography/` cuyo body es `http://localhost:9000/backend/api/cartographies/4393`.

6. Pulsamos Tornar.

7. Volvemos a seleccionar la tarea 33:
   - Vemos que el campo Cartografia tiene valor. Esto se debe a que `http://localhost:9000/backend/api/tasks/33/cartography?projection=view` devuelve con una respuesta 200 Ok el JSON que describe la cartografía con identificador 4393.

### Justificación del Comportamiento

Este comportamiento no está bien documentado en Spring Data Rest porque los creadores de Spring Data Rest piensan que es un comportamiento [obvio](https://github.com/spring-projects/spring-data-rest/issues/2384) 🤦 

>  Wouldn't documenting that both cases return a 404 Not Found be documenting the obvious? If a resource does not exist, 404 is the natural status code by definition, isn't it?

No todos los 404 que te encuentres están relacionados con este comportamiento. Solo los que están directamente relacionados con Spring Data REST. ¿Cómo saberlo? En este caso, `http://localhost:9000/backend/api/tasks/33/cartography/` aparece declarado en el elemento `_link` del esquema HAL de `http://localhost:9000/backend/api/tasks/33`. En otros similares, en caso de duda, habría que hacer la misma búsqueda.

**Comment by fjlopez** [comment]
> Voy a abrir una nueva issue para este error de request

#181 es inválida ya que es un comportamiento de la API.
