### ISSUE TITLE
Layers in a Service

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#18]
- The table in the Service editing form called 'Selecciona les capes que vols donar d'alta' should change its name to something like 'Capes registrades/noregistrades'.

- Missfunctionality in the 'Add' button. It shouldn't list all the layers registered in SITMUN but the layers in the service. The original idea for this table was that it should list all the layers contained in the service. The layers already registered in SITMUN admin database was to be marked with a checkbox.

**Comment by codinachssm** [comment]
The 'Get data' button returns an error: "undefined undefined"

**Comment by lucenasj** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/112

**Comment by IDEmenorca** [comment]
The table 'selecciona les capes que vols donar d'alta' doesn't list anything. The button 'Register' do not work.

**Comment by gon-nexus** [comment]
Did you click on the obtain data button? When doing this is when layers are listed and the registration button can be used.
@IDEmenorca
