### ISSUE TITLE
Request Incorrecta en Tasques Basiques

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#181]
@fjlopez existe un error de una request, reproducible en las siguientes branchs:

Sitmun-application-stack: feature-4
Sitmun-admin-app: Updates
Sitmun-backend-core: app-stack-feature-4
Otros: main
Acciones para reproducir el error:

Desde sitmun-application-stack ejecutaremos docker compose up
En el Menu Lateral -> Tasques -> Bàsiques -> 33 (Por ejemplo)
Si visualizamos las request Network, podemos ver que:
http://localhost:9000/backend/api/tasks/33/availabilities?projection=view -> funciona correctamente
http://localhost:9000/backend/api/tasks/33/cartography?projection=view -> devuleve 404 not found

**Comment by fjlopez** [comment]
~~Muévelo a sitmun-admin-core~~

> No es un bug, es una feature

Ver explicación en https://github.com/sitmun/sitmun-admin-app/issues/173#issuecomment-2220738730
