### ISSUE TITLE
Parameter tables inside editing FORM

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#19]
I don't understand the purpose of the three buttons (delete, undo, redo) on the settings / relationships table of the edit form. Do they have any functionality?

![image](https://user-images.githubusercontent.com/48914626/110356190-46d8bd80-803a-11eb-9a95-5f2d73b82168.png)

**Comment by lucenasj** [comment]
Yes, you can change for example the name of the entity that you have link with the entity
