### ISSUE TITLE
AG Grid unable to use rowModelType clientSide

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#195]
**How to reproduce it?**

- Clone the project:

`git clone --branch feature-4 --recurse-submodules https://github.com/sitmun/sitmun-application-stack.git`

- Navigate to the project directory:

`cd sitmun-application-stack`

- Check that the branch Updates of sitmun-admin-app is selected.

`git submodule status`

Must output a line that contains the string front/admin/sitmun-admin-app (remotes/origin/Updates)

- Build the Docker image without using the cache:

`docker compose build --no-cache`

- Run the Docker containers:

`docker compose up -d`

**Errors:**

In the console tab, in the developers tools of the browser, we can see that the problems seems to be realted to ag-grid

![image](https://github.com/user-attachments/assets/af4fe570-986c-4727-a030-a49a0d40b94b)

_Originally posted by @albertcoro in https://github.com/sitmun/sitmun-admin-app/issues/185#issuecomment-2258031170_

**Comment by albertcoro** [comment]
Update on the problem, reinstalled materials as it seems it was a major culprit of the problem. Now both tables and styles start to work, still major issues with missing styles and table functionalities

**Comment by albertcoro** [comment]
Visible on the sitmun-admin-app Updates branch

**Comment by fjlopez** [comment]
Let me know if you need help reviewing functionalities.

**Comment by albertcoro** [comment]
First I'll try to fix the styles and then I'll take a closer look at the missing functionalities.

**Comment by lucenasj** [comment]
Fixed   [https://github.com/sitmun/sitmun-admin-app/commit/2935550dc94cbab992cafeaa4589f1e40c629944]
