### ISSUE TITLE
New application configuration showing lots of groups and lots of layers in configuration JSON

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-admin-app#196]
**Describe the bug**
A new application has been created with only three layers added in the tree, but when going to the JSON returned by the API for this application it returns lots of layers and lots of groups.

**To Reproduce**
1. Go to sitmun admin page
2. Configure app as follows:
![image](https://github.com/user-attachments/assets/b4e93a0d-2477-4070-9624-42441fe9cfbb)

![image](https://github.com/user-attachments/assets/75e234ef-6d21-48fb-8d11-003a22272d8f)

![image](https://github.com/user-attachments/assets/321ba3bb-2e70-45c7-a2ed-15e8420cd5a5)

![image](https://github.com/user-attachments/assets/004dcd20-9b24-46cd-b067-4647a8de34d2)

![image](https://github.com/user-attachments/assets/c9b21995-ff2e-467d-951f-c2ba20e6480f)

![image](https://github.com/user-attachments/assets/2855320f-1747-49a1-859f-ab07ee7d9b24)

Being the tree like this:
![image](https://github.com/user-attachments/assets/5c668923-0e72-488c-8184-310be098d49d)

4. Save configuration
5. Call API for this app
6. See JSON and error

![Captura de pantalla 2024-08-06 122718](https://github.com/user-attachments/assets/28d9f204-a74c-4ab9-bb72-a87f7762703d)

![image](https://github.com/user-attachments/assets/a35edffe-e4ba-4d78-8fa9-aafa40d9530c)

**Expected behavior**
The JSON should show only the layers added in the tree.

**Comment by fjlopez** [comment]
Please, attach the JSON produced by the backend.
Did you have used the legacy `sitmun admin app` or the updated `sitmun admin app`?
Could you reproduce the problem in a clean `sitmun-application-stack` deployment?

**Comment by mvinent** [comment]
Finally I found out that the layers came from the role, so the JSON lists all the layers to which the role has access, whether they are needed or not.
If this is the expected behavior, we can close this issue as a non-issue. Sorry for the misunderstanding.
