### ISSUE TITLE
Drop-Down List Controls Do Not Honor Default Values from Code Lists

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#198]
**Bug Description**
Default values from code lists are not being honored in drop-down list controls.

**Steps to Reproduce**
1. Open the application.
2. Navigate to 'Servei'.
3. Click on 'Nou'.
4. Observe the following errors:
    - The drop-down list for `Mètode d'autenticació` has no value selected when it should display `None`, the default value from the `service.authenticationMode` code list.
    - The drop-down list for `Tipus` has `AIMS` selected, but it should have no value selected since there is no default value specified in the `service-type` code list.

**Expected Behavior**
When a drop-down list is restricted by a controlled list:
- If a code list has a `defaultCode` value, that value should be selected by default when a new service is created.
- If a code list does not have a `defaultCode`, the drop-down list should start without selecting a value when a new service is created.
 
**Screenshots**
<img width="1496" alt="Captura de pantalla 2024-08-08 a las 16 37 05" src="https://github.com/user-attachments/assets/cdef74da-cd41-477e-affe-13ab1505bfa4">

**Comment by fjlopez** [comment]
Related with:
- #155

**Comment by silmeUsil0001** [comment]
When creating  a new service, the  drop-down list for "Mètode d'autenticació" has the value selected:

![image](https://github.com/user-attachments/assets/cdc58f87-15f4-46f3-a5ea-4022bf571cce)

Also the drop-down list for Tipus has no value selected since there is no default value specified in the service-type code list.
