### ISSUE TITLE
Edit button in grids has disapeared

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-admin-app#199]
**Describe the bug**
I have installed the branch 'feature-4' from the sitmun-application-stack in my local machine and I have noticed that the 'edit' button has disapeared from multiple grids. It has disapeared from the 'Connection', 'Service' , 'Layers', 'Trees' and probablyany other grid.
So, now it's not possible to edit an existing element in this grids.

**To Reproduce**
1. Go to admin
2. Click on any module that has a grid ('Connection', 'Service' , 'Layers', 'Trees', etc.)
4. See grid
5. See that there is no edit button

**Expected behavior**
To have the edit button visible and working.

**Screenshots**
**The expected grid with the edit button:**
![image](https://github.com/user-attachments/assets/d1008d8a-b12c-45a1-88d5-025ec2b0f156)

**Actual grid, without the edit button:**
![image](https://github.com/user-attachments/assets/b20d7680-ae81-4fb0-9952-977531c531f7)

**Comment by fjlopez** [comment]
Fixed with https://github.com/sitmun/sitmun-application-stack/commit/8a50695dd6c5c4414d90ffc8f9e861734213464b
