### ISSUE TITLE
Migration from AG10 to AG16

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-admin-app#200]
Fixed pending bugs from migration app to AG16. Push to Updates Branch

**Comment by fjlopez** [comment]
https://github.com/sitmun/sitmun-application-stack/commit/da01c10c97b337a847d69834746ebd119e36616c updated to the latest commits (https://github.com/sitmun/sitmun-admin-app/commit/1e14df810a5927de0238bbf41f281ea3efce06f7)
