### ISSUE TITLE
Dashboard Display Issues: Oversized KPI Fonts, Inconsistent Layout, and Missing Data Indicators

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#201]
**Describe the bug**

**1. KPI Mini Cards Font Size**: The fonts used in the KPI mini cards are significantly oversized in some scenarios. This issue results in truncated information, particularly on smaller screens like laptops, where the entire dashboard becomes difficult to view without scrolling. 

**2.	Inconsistent Layout Across Devices**: The layout of the dashboard does not adapt well to different screen sizes. The arrangement of cards and charts is inconsistent, leading to an unorganized appearance, especially when transitioning between larger displays (e.g., Ultra HD monitors) and smaller ones (e.g., laptops).

**3. Missing Data Indicators on Chart Cards**:  A chart cards display a blank area instead of informing the user that data is not available yet. This can confuse users who may assume the charts are not functioning correctly or are still loading.

**To Reproduce**
1. Go to 'http://localhost:9000/admin/#/dashboard'
2. Observe the font size on the KPI mini cards, particularly on different screen sizes.
3. Check the layout consistency of the cards and charts across devices.
4. Observe the behavior of chart cards with no data.

**Expected behavior**

- **KPI Mini Cards**: Fonts should be resized to adhere to Material Design guidelines, ensuring the content is fully visible and proportionate to the card size, across all screen sizes.
- **Consistent Layout**: The dashboard layout should be responsive and maintain a consistent and organized structure across various devices, from large monitors to laptops.
- **Clear Data Indicators**: Chart cards with no available data should display a message such as “Data not available yet,” ensuring users are aware of the reason for the empty chart space.

**Screenshots**

- **Full screen (LG Ultra HD):**
<img width="2557" alt="Captura de pantalla 2024-08-29 a las 11 05 20" src="https://github.com/user-attachments/assets/6fcdff8c-8e08-43ff-b6f0-e236b3140cb4">

- **Full screen (Laptop):**

<img width="1512" alt="Captura de pantalla 2024-08-29 a las 11 06 15" src="https://github.com/user-attachments/assets/ccf01a5c-38e2-45e1-ae71-1307b7c16f0a">

**Desktop (please complete the following information):**
 - **OS**: macOS 14.6.1
 - **Browser**: Chrome
 - **Version**: 128.0.6613.85

**Comment by albertcoro** [comment]
Awaiting #212 getting solved to continue this one

**Comment by fjlopez** [comment]
Check https://github.com/sitmun/sitmun-admin-app/issues/212#issuecomment-2358455942

**Comment by albertcoro** [comment]
Fixed the issues and pushed to Updates

**Comment by fjlopez** [comment]
There appears to be a problem with the handling of empty data during startup. When the application starts, the charts are displayed before the necessary data is available (it takes around 60 seconds for the first computation). As a result, the charts appear as shown in the screenshot below:

<img width="1489" alt="Captura de pantalla 2024-09-19 a las 17 53 08" src="https://github.com/user-attachments/assets/04d350c7-dfbf-4734-8254-51320edb8397">

Only one out of the three charts displays the `No disponible` tag, but all of them should show this tag when data is unavailable. This suggests that the logic governing data availability is only applied to the "Usuaries" chart and not to the others.

**Steps to Reproduce:**

1. Run the following commands:
   ```bash
   docker compose down -v
   docker compose up -d
   ```
2. Navigate to: [http://localhost:9000/admin/#/dashboard](http://localhost:9000/admin/#/dashboard)

**Expected Behavior:**

All charts should display the `No disponible` tag until the data is available.

**Comment by albertcoro** [comment]
Fixed the issues and pushed to Updates

**Comment by fjlopez** [comment]
**Solution Review:**

This solution lacks coherence. The three charts are initially empty because the data is either not yet computed or unavailable. The main issue is that the application cannot distinguish between whether the data is still loading or not present at all. To address this, the logic must be consistent across all charts, displaying the message _No disponible_ whenever data is unavailable. It’s important to remember that at any given moment, any chart might lack data.

<img width="1386" alt="Captura de pantalla 2024-09-23 a las 11 40 42" src="https://github.com/user-attachments/assets/6ded4594-81f7-48ab-aed8-3be92f30a048">

**Expected Behavior (clarified):**

All charts should display the `No disponible` tag when the data is not available, which could occur at any time.

**Comment by albertcoro** [comment]
Fixed and pushed to Updates
