### ISSUE TITLE
AG Grid Configuration Warnings in Console

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#202]
**Describe the bug**

When interacting with certain grids on the application, several warnings related to AG Grid configuration appear in the browser console. These warnings suggest potential misconfigurations that may impact the grid's behavior and user experience. The specific warnings identified are:

- **Invalid `gridOptions.localeTextFunc`:** The console indicates that the `localeTextFunc` option is not recognized and may need to be replaced or corrected.
- **Unhandled Cell Data Type (Object):** The grid is encountering cell data with a type of "object," but no corresponding value formatter or parser has been provided, which could result in incorrect data display.
- **Invalid `colDef` Property (`singleSelection`):** The property `singleSelection` is being flagged as invalid in the `colDef`, which may lead to unintended grid behavior.

**To Reproduce**

1. Click on an option in the left-hand drawer menu (e.g., "Group Tasca").
2. Wait for the grid to load and display.
3. Open the browser's developer console.
4. Reload the page to observe the console logs.
5. Note the warnings related to AG Grid configurations, such as:  `AG Grid: invalid gridOptions property ‘localeTextFunc’ did you mean any of these: localeText, getLocaleText, onFieldPickerValueSelected, enableChartToolPanelsButton, preventDefaultOnContextMenu, onChartCreated, onChartDestroyed, loadingCellRenderer`

**Expected Behavior**

AG Grid should be configured correctly without any console warnings. For example:

- The `gridOptions.localeTextFunc` should either be correctly implemented or replaced with a valid property.
- Object-type cell data should be handled appropriately with a designated value formatter and parser.
- The `singleSelection` property in `colDef` should either be replaced with a valid alternative.

**Desktop (please complete the following information):**
 - **OS**: macOS 14.6.1
 - **Browser**: Chrome
 - **Version**: 128.0.6613.85

**Comment by fjlopez** [comment]
The configuration issues appears also in other places where AG Grid is used (e.g. http://localhost:9000/admin/#/connection/1/connectionForm)

**Comment by fjlopez** [comment]
In http://localhost:9000/admin/#/service/166/serviceForm warns `AG Grid: setQuickFilter is deprecated. Please use 'api.setGridOption('quickFilterText', newValue)' or 'api.updateGridOptions({ quickFilterText: newValue })' instead.`

**Comment by gon-nexus** [comment]
It should be fixed with the last two commits on Updates branch!

**Comment by fjlopez** [comment]
I'll check this evening.

**Comment by fjlopez** [comment]
Seems fixed!
