### ISSUE TITLE
"Registrar" Button in "Capes del servei" Does Not Save Data in serviceForm

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#203]
**Describe the bug**

The "Registrar" button in the "Capes del servei" section of the "serviceForm" (e.g., `http://localhost:9000/admin/#/service/166/serviceForm`) is active but does not perform any action when clicked. Specifically, clicking the button does not save the new layers (`Capa no registrada`) that have been added.

**To Reproduce**

1. Go to the `Servei` section.
2. Edit the service named `DIBA - Adreces`.
3. Click on `Actualitzar dades`.
4. Navigate to `Capes del servei`.
5. Notice that new layers appear as `Capa no registrada`.
6. Click `Registrar` but observe that nothing happens (new layers continue as `Capa no registrada`).
7. Click `Desa` but observe that nothing happens (new layers continue as `Capa no registrada`).

**Expected behavior**

- Changes in "Capes del servei" should be saved to the backend when "Desa" is clicked.
- When "Registrar" is clicked, only changes in "Capes del servei" (particularly new layers) should be saved.

**Screenshots**

<img width="1300" alt="Captura de pantalla 2024-08-29 a las 12 38 11" src="https://github.com/user-attachments/assets/87f0aee8-cc3f-4f25-a966-4568b80f014b">

**Desktop:**

- **Operating System:** macOS 14.6.1
- **Browser:** Chrome
- **Browser Version:** 128.0.6613.85

**Comment by fjlopez** [comment]
@silmeUsil0001 @IDEmenorca @mvinent Could you review this bug and confirm the expected behaviour?

**Comment by RicardCots** [comment]
I've tried to reproduce the error (in a local windows installation, using Firefox and also Chrome). I have not been able to reproduce it.  So far it works properly.

I propose the closure of the issue
