### ISSUE TITLE
Inconsistent and Difficult-to-Use Modal Dialogs Across the Application

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#204]
**Describe the bug**

All modal dialogs throughout the application are difficult to use, especially when they contain multiple tables or other interactive elements. The current design requires excessive scrolling to access content within the modal, which hampers user experience. Additionally, these modals are not styled consistently with the rest of the application.

**To Reproduce**
1. Navigate to any section that utilizes modal dialogs (e.g., `Rol`).
2. Trigger a modal dialog (e.g., by editing a role and adding a combination of territory and users).
3. Observe that while the first table or element is visible, scrolling is required to see additional content.

**Expected behavior**

Modal dialogs should follow the same design principles as standard forms within the application. Content within modals, especially tables, should be organized using Material Design Accordions, with each section or table placed within an Expansion Panel. This approach would allow users to expand or collapse sections as needed, reducing the need for excessive scrolling and maintaining consistency with the application's overall design.

**Screenshots**

**Current Look:** Example of a modal with tables (only one table is shown, requiring scrolling to see others):
  
<img width="1300" alt="Captura de pantalla 2024-08-29 a las 12 54 48" src="https://github.com/user-attachments/assets/f9b28513-4bf9-47a1-a43b-4c315ff1a708">

**Expected Look:** Example of how the tables should look with Material Design Accordions and Expansion Panels:
 
<img width="1300" alt="Captura de pantalla 2024-08-29 a las 12 55 28" src="https://github.com/user-attachments/assets/eba93c5d-070a-4d84-a360-0b276e468c5c">

**Desktop:**

- **Operating System:** macOS 14.6.1
- **Browser:** Chrome
- **Browser Version:** 128.0.6613.85

**Comment by fjlopez** [comment]
@IDEmenorca @silmeUsil0001 @mvinent could you review and confirm this issue?

**Comment by RicardCots** [comment]
Confirmed. It should be improved as described

**Comment by mvinent** [comment]
Validated https://github.com/sitmun/sitmun-admin-app/commit/3ee80b4329a5ec6bdc5b1e48fd7053494573fcaf
