### ISSUE TITLE
Error Messages Disappear Too Quickly and Are Not Logged in Console

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#205]
**Describe the bug**

Error messages that appear on the screen during user interactions disappear too quickly, making it difficult for users to read and understand the issue. Additionally, these error messages are not logged in the console, which hinders debugging efforts. While the console may display related errors, the specific error message shown on the screen is not captured in the console logs.

**To Reproduce**
1. Go to `Permisos sobre les capes`.
2. Select `Mapa de situació`.
3. Open the console.
4. Click on `Delete`.
5. Observe the modal error that briefly appears on the screen and then quickly disappears.
6. Notice that the error message shown on the screen is not logged in the console. The console may show a related error, but it does not include the specific message displayed on the screen.

**Expected behavior**

- The error message displayed on the screen should also be logged in the console to facilitate debugging.
- The on-screen error message should remain visible until the user acknowledges it, particularly during development. A confirmation button to close the modal could be added as an option during development to ensure that the message is fully reviewed.

**Screenshots**

- **On-Screen Error:**

<img width="1300" alt="Captura de pantalla 2024-08-29 a las 13 11 24" src="https://github.com/user-attachments/assets/147157cd-7d4b-44c5-9d7a-1a806cbf952e">

- **Console Output (Missing On-Screen Error Message):**

<img width="1300" alt="Captura de pantalla 2024-08-29 a las 13 15 44" src="https://github.com/user-attachments/assets/87e5c51e-fe95-4468-a374-335f5f392da5">

**Desktop (please complete the following information):**
 - **OS**: macOS 14.6.1
 - **Browser**: Chrome
 - **Version**: 128.0.6613.85

**Comment by albertcoro** [comment]
Problem solved and pushed to Updates branch
