### ISSUE TITLE
Parameter configuration tab in layer editing form

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#21]
- The parameter configuration tab in the layer editing form, should change its name to ' layer field configuration'... or something like that.

- Could it be programmed an action which allows to recover all the fields in the layer? As it happens in SITMUN 2.

![image](https://user-images.githubusercontent.com/48914626/110358998-4130a700-803d-11eb-978c-e9cb73323ef5.png)

**Comment by lucenasj** [comment]
It is necessary to create the request to get the layer fields and the answer must be treated to automatically add the parameters to the table. (4-days aprox.)
