### ISSUE TITLE
Unable to change the name of a folder in a layer tree.

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#213]
**Describe the bug**
Once created, it is not possible to change the name of a node in the layer tree. The administrator does not throw any error message but does not save the changes. 

**To Reproduce**
1. Go to any layer tree in SITMUn administrator'
2. Edit an existing folder containing layers.
3. Try to change its name

**Expected behavior**
Once the steps described above have been carried out, the name will be saved correctly. 

**Screenshots**
Editing a folder in the layer tree
![image](https://github.com/user-attachments/assets/2d381690-4120-41bd-903d-e6b91d6a6b16)

Changing its name
![image](https://github.com/user-attachments/assets/161cc367-5eac-4567-92be-5f3bf6288417)

Aparently it has changed but when clicking 'SAVE', changes disappear and the former name appears.
![image](https://github.com/user-attachments/assets/60496f34-10f2-44f4-8c41-0a432d5b402c)

![image](https://github.com/user-attachments/assets/53efab07-9b07-470c-aa25-ac651dd24c28)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version 128

**Comment by fjlopez** [comment]
There is a bug in the Trees Form component of the Administration application, affecting the `PUT` request used to update a tree node. The request body incorrectly assigns the value `UNDEFINED` to three boolean fields: `filterGetFeatureInfo`, `filterGetMap`, and `filterSelectable`, instead of the expected literals `null`, `false`, or `true`. This issue prevents any other modifications to the tree node from being processed.

Below is an example of the entity body generated by the Trees Form component that highlights the affected fields.

```json
{
  "name": "[Update]Instruments d'ordenació territorial",
  "tooltip": "Instruments d'ordenació territorial",
  "order": 0,
  "active": null,
  "datasetURL": null,
  "metadataURL": null,
  "description": "Instruments d'ordenació territorial",
  "filterGetFeatureInfo": "UNDEFINED",
  "filterGetMap": "UNDEFINED",
  "filterSelectable": "UNDEFINED",
  "style": null,
  "_links": {
    "self": {
      "href": "http://localhost:9000/backend/api/tree-nodes/12744"
    },
    "treeNode": {
      "href": "http://localhost:9000/backend/api/tree-nodes/12744",
      "templated": true
    },
    "cartography": {
      "href": "http://localhost:9000/backend/api/tree-nodes/12744/cartography",
      "templated": true
    },
    "parent": {
      "href": "http://localhost:9000/backend/api/tree-nodes/12744/parent",
      "templated": true
    },
    "tree": {
      "href": "http://localhost:9000/backend/api/tree-nodes/12744/tree"
    }
  }
}```

**Comment by silmeUsil0001** [comment]
When updating the name of a folder, the former name changes:

![image](https://github.com/user-attachments/assets/75cc067a-f19f-4544-8cfa-aae9099028c4)

![image](https://github.com/user-attachments/assets/fd9cd5e8-b994-48b6-b0a5-a5e8915b34d1)

When saving the tree, the changed names are correct:

![image](https://github.com/user-attachments/assets/937e4088-7b38-4fdd-8f47-a13a1fe96477)
