### ISSUE TITLE
Add the service name to the layer grid

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#214]
**Is your feature request related to a problem? Please describe.**
It would be very useful to have, in the layer grid that displays the layer list, the name of the service to which the layer belongs.

**Describe the solution you'd like**
See image:
![image](https://github.com/user-attachments/assets/667b0872-9202-4fce-abbb-dc09a51b69cb)

**Comment by fjlopez** [comment]
I think that the implementation of this is straightforward as the administration has already this information available: the property `serviceName` provided by the request `api/cartographies?projection=view`. This new column should be `read only`.

Excerpt form a real response of the backend. 
```.json
{
  "_embedded" : {
    "cartographies" : [ {
      "name" : "WMTS Bases - ICGC- Topo",
      "id" : 1,
      "type" : null,
      "description" : null,
      "order" : 0,
      "serviceName" : "ICC - Mapesmultibase",
      "blocked" : false,
```

**Comment by silmeUsil0001** [comment]
Service name column is appearing in the service grid form

![image](https://github.com/user-attachments/assets/05457d61-b046-4c45-b82e-14087f636f66)
