### ISSUE TITLE
Errors in the operation of the layer tree

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#220]
**Describe the bug**

If there are multiple layers in a layer tree and you want to reorder them by creating folders and moving each layer into the appropriate folder, the application does strange things when saving the changes. Normally it does not save all the changes and you have to do the same thing over and over again until all the layers are in the desired folder.

**To Reproduce**
1. Go to any layer tree.
2. Add different layers to the tree.
3. Create a new folder and try to move all new layers to that (or any other) folder.
4. Save and see how some changes revert and some layers go back to the initial position.

**Expected behavior**
Once save is clicked, tha application saves the tree as the user is seeing it.

**Comment by fjlopez** [comment]
@RicardCots, could you add a step by step description to repeat the bug?

**Comment by mvinent** [comment]
Validated https://github.com/sitmun/sitmun-admin-app/commit/3ee80b4329a5ec6bdc5b1e48fd7053494573fcaf
