### ISSUE TITLE
Layer tree

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#23]
- It is not possible to move a layer from one group into a different one.

- Once a folder is moved into another as a subfolder, it can not be relocated outside this folder.

- Sometimes it is impossible to alter the order of a layers in a folder.

.

**Comment by codinachssm** [comment]
I tested this issue and it still has problems, does the "Pending validation" status mean that it should now work correctly?

**Comment by gon-nexus** [comment]
This was fixed in a previous version, but a later update broken it (already fixed), with the next version it will work correctly!
