### ISSUE TITLE
Backend branch app-stack-feature-4 not working

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#230]
**Describe the bug**
While trying to compile the entire project through the Sitmun Stack project, I was stopped everytime by the backend. I tried changing branches, "--no-cache" and even deleting previous dockers of the stack. Nothing has worked.

**To Reproduce**
1. Clone the following [repository](https://github.com/sitmun/sitmun-application-stack), with the instructions in the readme
2. Select the following branches
   2a. Backend -> app-stack-feature-4
   2b. Sitmun-admin-app -> Updates
   2c. Middleware -> Main
   2d. Viewer-app -> Main
4. Execute "docker compose build --no-cache"

**Expected behavior**
Execution should work and start the application.

**Screenshots**
Screenshot of the docker stack, with backend failing:
![image](https://github.com/user-attachments/assets/80e7087e-9fe6-4e3d-91cd-999702cc22e2)

Screenshot of the errors in the developer tools in chrome:
![image](https://github.com/user-attachments/assets/8a1cc21a-abda-42d4-86b6-0290682d57b5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 130.0

**Comment by fjlopez** [comment]
Have you tried `docker compose down -v` (remove existing volume) and then `docker compose up -d`?

**Comment by albertcoro** [comment]
Solved, Thank you! It was docker compose down -v!
