### ISSUE TITLE
Create a layer with a set of layers of one or several services

### ISSUE THREAD

**Issue by ibarzrm** [sitmun/sitmun-admin-app#253]
**Describe the bug**
When creating a layer with several layers together and using it in a tree, the different layers are loaded separately in ‘Capas cargadas’ of the content, instead of the layer as a single element.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Capes'
2. Go to ‘Nou’
3. Define the name of several layers in the text box ‘Capes’, separated by commas
3. Include this layer in the Tree
4. Go to viewer and load the layer from ‘capas disponibles’. 
5. Check that in ‘Capas cargadas’ there are the different layers of origin.

**Expected behaviour**
See a single layer in ‘Capas cargadas’.

**Screenshots**
![image](https://github.com/user-attachments/assets/aa2787a1-0e82-47c7-8b5a-9ca8fb6c88c9)

![image](https://github.com/user-attachments/assets/dc0cf945-9d8e-4e14-bd7d-e0bc73f8352c)

 ‘Capas cargadas':
![image](https://github.com/user-attachments/assets/a354a77c-9f8d-4649-92e2-c7f789381215)

**Comment by fjlopez** [comment]
@mvinent Could you review this issue?

**Comment by mvinent** [comment]
Thw way it's working is the expected standard behavior. Here we are calling different layers of one service, so the client renders them as three different layers, any other behavior should be developed.

**Comment by fjlopez** [comment]
@ibarzrm, do you consider this issue solved with @mvinent comments?

**Comment by ibarzrm** [comment]
If this is the expected behaviour, the issue can be closed. 
In that case, I guess there is another way to make a layer with a set of layers of various services.
