### ISSUE TITLE
Nodes of a Layer

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#26]
Which is the meaning of each column of the Node section in the Layer editing form? Is it possible to see the name of the Tree that contains the Node?
![image](https://user-images.githubusercontent.com/38311286/111999060-e4dd8500-8b1c-11eb-8c2f-50f85e3c7a82.png)

**Comment by fjlopez** [comment]
>  Is it possible to see the name of the Tree that contains the Node?

@lucenasj I can add this info to the TreeNode projection if it is requested

**Comment by codinachssm** [comment]
Yes, please, add the Tree name. Without that, the Nodes panel is not useful. Thank you!

**Comment by fjlopez** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/102 moved to validation
