### ISSUE TITLE
Task menu

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#27]
The task list on the main menu should be obtained form the API (https://github.com/sitmun/sitmun-backend-core/issues/92), and clasified in two different levels. 

The first level list all the types. The second, only available for the edition task types, list the 4 different edition subtypes. 

The Task root menu shouldn't list any task.

![imagen](https://user-images.githubusercontent.com/26217441/114380142-0369f580-9b8a-11eb-9397-ed73339eee3a.png)

**Comment by fjlopez** [comment]
Already implemented
