### ISSUE TITLE
LAYER - Config Parameters edition

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#30]
TYPE and FORMAT parameters of the Layer Configuration Parameters panel should be updetable. Their values should come from a List.

**Comment by lucenasj** [comment]
It is necessary to develop a new type of AG-GRID column that is a list, and all required functionality must be developed. (4-days aprox)

**Comment by codinachssm** [comment]
OK,
But I have a question: In this panel I can choose any type of the list for the field TYPE, but it always shows only the rows that have the value "INFO". So, maybe the list should be filtered according to the possible values for this panel? Or the rows should not be filtered with the value INFO?

**Comment by codinachssm** [comment]
OK
