### ISSUE TITLE
USER POSITION Panel - Expiration date

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#32]
- The column Expiration should open a Calendar to fill the value.
- Even that I enter a valid format date (like 11/11/2021), the value is not saved after clicking to Save button.

**Comment by gon-nexus** [comment]
We have tried to reproduce the non-saving expiration date error but always the field is saved correctly, can you tell us which user were you editing and which user position are you trying to modify?
Thanks! @codinachssm

**Comment by codinachssm** [comment]
I tried it with the userId: user101, userName: Name of 101.
When I try to enter an expiration date, no calendar is opened (I suppose it should open a calendar). Then, I try to write a date, for example 26/05/2021, and the message "Invalid Date" is shown. Maybe this is why it doesn't save anything.
