### ISSUE TITLE
TERRITORY - bounding box decimals

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#34]
Decimals are not allowed in BBOX. If someone decides to use geographic coordinates this is a must. 

By the way, it would be useful to record the coordinate system that we are using in the 'generic' table (the table that contains the default administrator language)

**Comment by fjlopez** [comment]
@lucenasj BBOX can be provided by the API as a data structure rather as a string (e.g. minx, miny, maxx, maxy of reals). This could help to fix this issue. 

@montsemarco I agree with your proposal for the SRS. I think that such SRS should be the SRS of the BBOX, isn't?

**Comment by montsemarco** [comment]
@lucenasj It would be ok, if the others participants agree, of course.

@fjlopez Yes, I'm talking about the SRS of the BBOX. Is there any other parameter related with coordinates in the database? I have not seen it. I'd also like to ask if there is expected to show the content of this generic table (default language, SRS,...) in the administrator interface (maybe in a corner of the Dashboard or so?)

**Comment by fjlopez** [comment]
@lucenasj With https://github.com/sitmun/sitmun-backend-core/issues/99 this is fixed

**Comment by montsemarco** [comment]
The administrator let me put dots (.)  but also commas (,). Is this behaviour correct or it should be restricted to just commas or dots?

**Comment by fjlopez** [comment]
@montsemarco I just tested that if you use in the UI dots or commas for the decimal point, the request to the server contains always a valid JSON number (i.e where the decimal point is a dot) equivalent to the number entered in the UI control.

**Comment by montsemarco** [comment]
@fjlopez, with your explanation, I understand that the own interface corrects the inconsistency, hence, I consider the issue as solved
