### ISSUE TITLE
Several codelist are not multilanguage

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#37]
The codelist of "Format" field always shows in spanish. Location of this field: Layer Object, edit an item, go to the 'Spatial Selection' section and press Button 'New'.

The codelist of "Type" and "Type Value" fields always show in english. Location of this field: Layer Object, edit an item, go to the 'Territorial filter' section and press Button 'New'.

**Comment by montsemarco** [comment]
Aldo happens with the codelist of "Format" field in the layer configuration parameters. The controlled list of this field always shows in spanish. Location of this field: Layer Object, edit an item, go to the 'Parameter Configuration' section and press 'New' button .

**Comment by gon-nexus** [comment]
The request is made with the "lang" parameter, we cannot create the translations of these Codelists, I think you should tell @fjlopez  all the translations you need.

**Comment by fjlopez** [comment]
@montsemarco could you send a short list of translated values for codes in format, type and type value? I will add to the test dataset that the admin app uses so you can test the functionality.

**Comment by fjlopez** [comment]
@lucenasj, it is on the SITMUN community side rather than us

**Comment by montsemarco** [comment]
@fjlopez here below the short list of translated values. Changes to be made are indicated **in bold**.

Note.- Please, to standardize all the Administrator codelists, review that Number/Número/Número is used instead of Numeric/Numérico/Numèric. Review also that the Codelists always start with capital letters.

### Layers-Edit.Territorial filter,  New button:
Current values are in english:
- Type field: Custom, Defined
- Value Type field: Alphanumeric, Date, **Number**

Spanish translation proposal:
-  Type field: **Personalizado**, **Predefinido**
- Value Type field: **Alfanumérico**, **Fecha**, **Número**

Catalan translation proposal:
-  Type field: **Personalitzat**, **Predefinit**
- Value Type field: **Alfanumèric**, **Data**, **Número**

### Layers-Edit.Spatial selection,  New button:
 Currrent values are in spanish:
- Format field: Imagen, URL, fecha, número, porcentage, texto. Change first one in capital letters (Imagen, URL, **F**echa, **N**úmero, **P**orcentage, **T**exto)

English translation proposal:
- Format field: **Image**, **URL**, **Date**, **Number**, **Percentage**, **Text** 

Catalan translation proposal:
- Format field: **Imatge**, **URL**, **Data**, **Número**, **Percentatge**, **Text**

**Comment by fjlopez** [comment]
Done with https://github.com/sitmun/sitmun-backend-core/commit/58d9a6d88dcb79b82fb093734730bd7e10467c73
