### ISSUE TITLE
All passwords in the system should be masked

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#38]
- Go to the Connection Object, edit an element. The 'Password' field is not masked (with asterisks or so).
- Go to the User Object, edit an element. The 'Password' and 'Confirm password' fields are shown in blank. Would be nice to show a mask instead to indicate that the password has already been entered.

**Comment by fjlopez** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/103 moved into validation

**Comment by montsemarco** [comment]
I entered the password of a connection and the asterisks appears while writing, as expected.
However, when I press the "Save" button and I edit again this connection, the password field is empty. Now this field should be shown with asterisks, in order to know that a password has already been assigned to the connection.

The same happens with the user password and the user confirm password fields.

**Comment by montsemarco** [comment]
To know if a password has already been entered is indicated with a checkbox located next to the password field
