### ISSUE TITLE
cancel, redo, undo and accept buttons - unexpected behavior

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#39]
Unexpected behaviors will be explained throught examples:

Unexpected behavior 1.- Go to the 'Layer' Object. Modify several fields directly on the grid. The cells of the modified fields are shown correctly with a different background color. 
![imagen](https://user-images.githubusercontent.com/1905272/116374500-9f446400-a80e-11eb-806d-cedd53801280.png)
The problem is that, if I press the 'Accept' button to apply the changes and, afterwards, I continue modifying in the grid, the cells of the modified fields now are not shown in a different background color. 

This wrong behavior should be reviewed in all grids

Unexpected behavior 2.- Go to any Object, for instance, 'Connection' and modify several fields directly on the grid. Go to another Object, for instance 'Layers'. Then return again to the 'Connection' Object. As you can see, all the changes already made on the grid have been lost. This behavior maybe is correct, however, when clicking to another Object without having accepted the changes, it would be nice to inform with a message that all changes that have not been validated are going to be lost.

**Comment by lucenasj** [comment]
It is necessary to develop this functionality, which will detect us leaving a screen, and display a dialog by warning that unsaved changes will be lost. (2-days aprox)
