### ISSUE TITLE
LAYER Parameters/SpatialSelection

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#41]
When editing the "Spatial selection.Label" or "Parameter settings.Name" fields, in the LAYER grids, the message "Pendent modificació" is displayed. But changes are not saved after clicking at the SAVE button. Sometimes the following message is displayed: 

Http failues response for https://sitmun-backend-core.herokuapp.com
/api/cartografies/724: 400 OK

**Comment by fjlopez** [comment]
@codinachssm could you the data sent that causes the issue and the response from the server. You can use the web development tools of your web browser for this tasks.  With this data I can reproduce the problem in a test and confirm or discard if the problem is related to the backend and if the issue is related with the front I can provide hints to @lucenasj

**Comment by codinachssm** [comment]
In the attached file are the requests/responses involved in the action that causes the error. The number is the order of the calls. Number 6 is the one that causes the error.

The Console outputs the following information for this error:

polyfills.ff48e0ea8ec1a7f6f207.js:1 PUT https://sitmun-backend-core.herokuapp.com/api/cartographies/724 400
v @ polyfills.ff48e0ea8ec1a7f6f207.js:1
scheduleTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
onScheduleTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
scheduleTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
scheduleTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
scheduleMacroTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
p @ polyfills.ff48e0ea8ec1a7f6f207.js:1
(anonymous) @ polyfills.ff48e0ea8ec1a7f6f207.js:1
O.o.<computed> @ polyfills.ff48e0ea8ec1a7f6f207.js:1
(anonymous) @ main.62cf69e8514653d6d832.js:1
_trySubscribe @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
l @ main.62cf69e8514653d6d832.js:1
_innerSub @ main.62cf69e8514653d6d832.js:1
_tryNext @ main.62cf69e8514653d6d832.js:1
_next @ main.62cf69e8514653d6d832.js:1
next @ main.62cf69e8514653d6d832.js:1
(anonymous) @ main.62cf69e8514653d6d832.js:1
_trySubscribe @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
call @ main.62cf69e8514653d6d832.js:1
subscribe @ main.62cf69e8514653d6d832.js:1
onSaveButtonClicked @ main.62cf69e8514653d6d832.js:1
(anonymous) @ main.62cf69e8514653d6d832.js:1
pc @ main.62cf69e8514653d6d832.js:1
r @ main.62cf69e8514653d6d832.js:1
i @ main.62cf69e8514653d6d832.js:1
__tryOrUnsub @ main.62cf69e8514653d6d832.js:1
next @ main.62cf69e8514653d6d832.js:1
_next @ main.62cf69e8514653d6d832.js:1
next @ main.62cf69e8514653d6d832.js:1
next @ main.62cf69e8514653d6d832.js:1
emit @ main.62cf69e8514653d6d832.js:1
onSubmit @ main.62cf69e8514653d6d832.js:1
(anonymous) @ main.62cf69e8514653d6d832.js:1
pc @ main.62cf69e8514653d6d832.js:1
r @ main.62cf69e8514653d6d832.js:1
(anonymous) @ main.62cf69e8514653d6d832.js:1
invokeTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
onInvokeTask @ main.62cf69e8514653d6d832.js:1
invokeTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
runTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
invokeTask @ polyfills.ff48e0ea8ec1a7f6f207.js:1
g @ polyfills.ff48e0ea8ec1a7f6f207.js:1
_ @ polyfills.ff48e0ea8ec1a7f6f207.js:1
Show 27 more frames

This is the info showed just before the error:

0: {id: 245, name: "NVIA_CAR", value: "CARRER", format: "T", type: "INFO", …}
1: {id: 257, name: "DOCUMENT", value: "DOCUMENT O FITXA", format: "U", type: "INFO", …}
2: {id: 259, name: "IMATGE2", value: "FOTO", format: "F", type: "INFO", …}
3: {id: 258, name: "IMATGE1", value: "FOTO", format: "F", type: "INFO", …}
4: {id: 243, name: "TVIA_INE", value: "TIPUS VIA (INE)", format: "T", type: "INFO", …}
5: {id: 252, name: "URL", value: "WEB", format: "U", type: "INFO", …}
6: {id: 260, name: "IMATGE3", value: "FOTO", format: "F", type: "INFO", …}
7: {id: 255, name: "TITULARITAT", value: "TITULARITAT", format: "T", type: "INFO", …}
8: {id: 262, name: "IMATGE5", value: "FOTO", format: "F", type: "INFO", …}
9: {id: 254, name: "RESPONSABLE", value: "RESPONSABLE", format: "T", type: "INFO", …}
10: {id: 244, name: "NVIA_INE", value: "NOM VIA (INE)", format: "T", type: "INFO", …}
11: {id: 256, name: "ESTAT", value: "ESTAT", format: "T", type: "INFO", …}
12: {id: 246, name: "PORTAL", value: "NÚM. DE PORTAL", format: "T", type: "INFO", …}
13: {id: 261, name: "IMATGE4", value: "FOTO", format: "F", type: "INFO", …}
14: {id: 247, name: "ADRECA", value: "ADREÇA", format: "T", type: "INFO", …}
15: {id: 248, name: "PORTALC", value: "COMPLEMENT", format: "T", type: "INFO", …}
16: {id: 249, name: "COD_POSTAL", value: "CODI POSTAL", format: "T", type: "INFO", …}
17: {id: 3291, name: "DOC_INTERN", value: "FITXA INTERNA", format: "U", type: "INFO", …}
18: {id: 250, name: "TELEFON", value: "TELÈFON", format: "T", type: "INFO", …}
19: {id: 253, name: "OBS", value: "OBSERVACIONS", format: "T", type: "INFO", …}
20: {id: 251, name: "EMAIL", value: "E-MAIL", format: "T", type: "INFO", …}
length: 21
__proto__: Array(0)

And the info right after the error:

Li {headers: $n, status: 400, statusText: "OK", url: "https://sitmun-backend-core.herokuapp.com/api/cartographies/724", ok: false, …}error: nullheaders: $n {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure response for https://sitmun-backend-core.herokuapp.com/api/cartographies/724: 400 OK"name: "HttpErrorResponse"ok: falsestatus: 400statusText: "OK"url: "https://sitmun-backend-core.herokuapp.com/api/cartographies/724"__proto__: oi

If you need another type of information, please tell me. I can reproduce this error everytime.
[headers.zip](https://github.com/sitmun/sitmun-admin-app/files/6405340/headers.zip)

**Comment by fjlopez** [comment]
I need the body of the requests and repsonses. Follow these instructions to obtain a HAR file that describes your interaction with the backend.

https://www.medianova.com/en-blog/2019/07/15/a-step-by-step-guide-to-generating-a-har-file

**Comment by codinachssm** [comment]
OK. I upload the .har file.
[sitmun.github.io.zip](https://github.com/sitmun/sitmun-admin-app/files/6413030/sitmun.github.io.zip)

**Comment by fjlopez** [comment]
@lucenasj the client is doing a bad request. 

The problem is:
```
Could not read an object of type class org.sitmun.plugin.core.domain.Cartography from the request!; 
nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: 
Cannot deserialize value of type `java.lang.Boolean` from String \"0\": only \"true\" or \"false\" recognized
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.sitmun.plugin.core.domain.Cartography[\"applyFilterToGetFeatureInfo\"])
```

The cause is that in the request  `applyFilterToGetFeatureInfo` and `applyFilterToSpatialSelection` are integer values (0 or 1) instead of bolean values (true or false).

To help you to find and solve quickly these client bugs, I just pushed a change in the backend  (see https://github.com/sitmun/sitmun-backend-core/issues/98) that:
- To find them the backend response returns a 422 status code instead of 400 when the JSON cannot be processed 
- To solve them the backend response provides a better description of the error so it can be fixed quickly

**Comment by gon-nexus** [comment]
The problem comes from the test data, the parameters that arrive have as "value" the values "0" or "1", instead of "true" or "false", and since it is not being edited, it is resent with this value.

The values of "spatial selection" and "parameter" are not stored because the layers save request fails (for the reason mentioned above), to try it, these checkboxes can be demarcated and it will work! (Or uncheck and re-mark them)
![image](https://user-images.githubusercontent.com/73172087/116987567-8258d680-accf-11eb-8a61-4a78936ae466.png)

 (If it's not a lot of work, could you change it to check that everything works well? Or if the real data will have these values, tell me and I will control it @fjlopez )

**Comment by fjlopez** [comment]
Test data and API are OK: the properties `applyFilterToGetFeatureInfo` and `applyFilterToSpatialSelection` are both boolean *nullables* in the data model and only return JSON Boolean values `true` or `false` or `null` in the API Web.  Maybe booleans are converted to 0/1 when you set or read data in these checkboxes by a bug, so when you send the `PUT` request boolean values are turned into integers.

*Edit*: fixed as fields are new and test data is `null`.

**Comment by montsemarco** [comment]
I just made the same test as Marta and I got exactly the same behavior. I attach the har file.
I tested it one week ago and it was working properly in my cimputer. I don't know why now is not working .

[sitmun.github.io_marcosm_chrome.zip](https://github.com/sitmun/sitmun-admin-app/files/6441682/sitmun.github.io_marcosm_chrome.zip)

**Comment by fjlopez** [comment]
The POST request of @montsemarco is a JSON that encodes two boolean properties (`applyFilterToGetFeatureInfo` and `applyFilterToSpatialSelection`) a integer encoded as strings:

```json
...
"description":null,
"datasetURL":null,
"applyFilterToGetFeatureInfo":"0",
"applyFilterToSpatialSelection":"1",
"queryableFeatureEnabled":true,
"queryableFeatureAvailable":false,
...
```
instead of

```json
...
"description":null,
"datasetURL":null,
"applyFilterToGetFeatureInfo":false,
"applyFilterToSpatialSelection":true,
"queryableFeatureEnabled":true,
"queryableFeatureAvailable":false,
...
```

@lucenasj as SITMUN Admin App uses <https://sitmun-backend-core.herokuapp.com/api/cartographies/724?projection=view> to fill the form and it returns:
```json
...
"description":null,
"datasetURL":null,
"applyFilterToGetFeatureInfo":null,
"applyFilterToSpatialSelection":null,
"queryableFeatureEnabled":true,
"queryableFeatureAvailable":true,
...
```
the problem is with the logic of apply filter in SITMUN Admin App. `applyFilterXXX` are boolean nullable in the model.

**Comment by codinachssm** [comment]
I tested it again and it seams the .har is different but the result is the same: it doesn't save my change when I click at the DESA button. And the first time I test it, I get the follwing error message:
![image](https://user-images.githubusercontent.com/38311286/117774735-17148480-b23a-11eb-90bf-fdf66e875380.png)

I attach the .har file. 
[sitmun.github.io_codinachssm_20210511_chrome.zip](https://github.com/sitmun/sitmun-admin-app/files/6457213/sitmun.github.io_codinachssm_20210511_chrome.zip)

And at the Console tab I can see the following error message:
polyfills.ff48e0e….js:1 PUT https://sitmun-backend-core.herokuapp.com/api/cartography-parameters/241 400
main.4158390….js:1 
ERROR 
li {headers: $n, status: 400, statusText: "OK", url: "https://sitmun-backend-core.herokuapp.com/api/cartography-parameters/241", ok: false, …}
error: {errors: Array(1)}
headers: $n {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for https://sitmun-backend-core.herokuapp.com/api/cartography-parameters/241: 400 OK"
name: "HttpErrorResponse"
ok: false
status: 400
statusText: "OK"
url: "https://sitmun-backend-core.herokuapp.com/api/cartography-parameters/241"
__proto__: oi

**Comment by fjlopez** [comment]
The message error send by the backend is the following:
```json
{ "errors" : [ {
   "entity" : "CartographyParameter",
   "property" : "format",
   "invalidValue" : "T",
   "message" : "Invalid value"} ]
}
```
This are the allowed values for `format` property in `CartographyParameters`:

```sql
-- STM_PAR_GI.PGI_FORMAT
-- TODO Validate value and description of code list cartographyParameter.format
INSERT INTO STM_CODELIST
VALUES (18, 'cartographyParameter.format', 'Imagen', false, 'Imagen');
INSERT INTO STM_CODELIST
VALUES (19, 'cartographyParameter.format', 'número', false, 'número');
INSERT INTO STM_CODELIST
VALUES (20, 'cartographyParameter.format', 'porcentaje', false, 'porcentaje');
INSERT INTO STM_CODELIST
VALUES (21, 'cartographyParameter.format', 'texto', false, 'texto');
INSERT INTO STM_CODELIST
VALUES (22, 'cartographyParameter.format', 'URL', false, 'URL');
INSERT INTO STM_CODELIST
VALUES (23, 'cartographyParameter.format', 'fecha', false, 'fecha');
``` 
After a review in the data, it seems that the list must be updated as the values in the third column does not correspond with the test data.  My best guess is:
```sql
-- STM_PAR_GI.PGI_FORMAT
-- TODO Validate value and description of code list cartographyParameter.format
INSERT INTO STM_CODELIST
VALUES (18, 'cartographyParameter.format', 'I', false, 'Imagen');
INSERT INTO STM_CODELIST
VALUES (19, 'cartographyParameter.format', 'N', false, 'número');
INSERT INTO STM_CODELIST
VALUES (20, 'cartographyParameter.format', 'P', false, 'porcentaje');
INSERT INTO STM_CODELIST
VALUES (21, 'cartographyParameter.format', 'T', false, 'texto');
INSERT INTO STM_CODELIST
VALUES (22, 'cartographyParameter.format', 'U', false, 'URL');
INSERT INTO STM_CODELIST
VALUES (23, 'cartographyParameter.format', 'F', false, 'fecha');
``` 
@codinachssm can you confirm these values?

**Comment by codinachssm** [comment]
Right now we have the following values in **STM2**:
SELECT DISTINCT PCA_TIPO, PCA_FORMATO FROM STM_PARAMCAR ORDER BY 1, 2;
PCA_TIPO                             PCA_FORMATO
-----------------------------  ----------------------------------
EDIT                                     C
EDIT                                     F
EDIT                                     N
EDIT                                     T
EDIT                                     U
FILTRO
FILTRO_ESPACIAL
FILTRO_INFO
INFO                                     D
INFO                                     F
INFO                                     N
INFO                                     P
INFO                                     T
INFO                                     U
INFOSELECT                          N
INFOSELECT                          T
SELECT                                   N

As this issue is focused on the INFO/INFOSELECT types, possible values right now at **STM2** are: D, F, N, P, T, U. And the meaning:
D: fecha
F: imagen
N: número
P: porcentaje
T: texto
U: URL
 
Please, could you change the INSERT for "Imagen" to "imagen"?

**Comment by codinachssm** [comment]
Please, ignore the text "could you change the INSERT for "Imagen" to "imagen"?" as @montsemarco opened an issue to standardize all code list texts: "Several codelist are not multilanguage #37".

**Comment by fjlopez** [comment]
@codinachssm done with https://github.com/sitmun/sitmun-backend-core/commit/58d9a6d88dcb79b82fb093734730bd7e10467c73
