### ISSUE TITLE
New properties Application / Territory

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-admin-app#43]
1. Required new relationship Application-Territory.
2. Required new propertires:

- Center Coordinates
- Initial Zoom
- Default Basemap (relationship with background table)

3. New expansion panel on Application page to manage this relationship and properties

**Comment by fjlopez** [comment]
Need some clarifications, as they affect to the backend
1. Application and Territory have an indirect relationship through Role and UserConfiguration. Is the idea to compute the existing Territories through this relationship and show the list read only?
1. I assume that the new properties are for the Application, isn't?
   1. Center coordinates can be returned as JSON objects`{"x": nn.nn, "y": nn.nn}` for example; a similar approach can be done with `extent` (now is a string)
   2. Initial Zoom, a number?
   3. default basemap could redundant as application backgrounds have an `order` field: e.g. the basemap with the lower `order` field could be considered as the default.

**Comment by lucenasj** [comment]
It is necessary to create a new table in the detail of an application, to display this new relationship, the add button will add a territory, and then from the same table, all other properties will be modified (4 days aprox.)

**Comment by fjlopez** [comment]
After a meeting with the SITMUN TC only the coordinates are required and the other features require further analysis.

**Comment by fjlopez** [comment]
@lucenasj Territory has now two additional properties:

- `defaultZoomLevel`: integer, optional
- `center`: a point (`x` and `y` properties as usual, same semantics as extent), optional

if `center` is unset and  `extent` is set in the database, the returned value is the centroid of the extent.
