### ISSUE TITLE
Layers-edit -> Nodes element buttons

### ISSUE THREAD

**Issue by montsemarco** [sitmun/sitmun-admin-app#45]
When editing a layer, there is a "Nodes" section with four buttons: the 'Add" button on the right and the "cancel", "undo" and "redo" buttons on the left.

- If nodes can be added from here, then the "Delete" button is missing. 
- However, if the "Nodes" section is just for informational purposes, that is, nodes must be created inside the tree element, all four buttons should be removed .

**Comment by codinachssm** [comment]
Also, the Node name column should not be editable, as I think this is just an informative panel.

**Comment by codinachssm** [comment]
The "Status" column should also be removed if no changes can be made here.

**Comment by montsemarco** [comment]
Now is correct, that is, the "Nodes" section has no buttons because is just for informational purposes. 

However, before closing the issue, the checkbox should be removed from the interface. 
Since no actions can be done in the "Nodes" object that checkbox is useless,

![nodesCheckbox](https://user-images.githubusercontent.com/1905272/122738259-213a9180-d282-11eb-8129-698c01e23d1c.png)
