### ISSUE TITLE
TASKS - BASICS

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#46]
It seems the content of this grid is the same as the Query task. It seams an error.

**Comment by codinachssm** [comment]
In the Basic Task Edit panel, I think the Cartography field should not be mandatory. A task can be independent of any layer.

**Comment by codinachssm** [comment]
Issue: "It seems the content of this grid is the same as the Query task. It seems an error." --> OK
Issue: "In the Basic Task Edit panel, I think the Cartography field should not be mandatory. A task can be independent of any layer." --> I keep seeing the * symbol which means it is a requeried field

**Comment by gon-nexus** [comment]
To be able to set cartography not requiered we need to modify the specification of the task, which is already sent to Unizar, when they update the specification cartography won't be a required field anymore

**Comment by fjlopez** [comment]
@gon-nexus done https://github.com/sitmun/sitmun-backend-core/issues/111
