### ISSUE TITLE
FME Extraction task

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#47]
Columns Cartography-Service-Layer are empty.

**Comment by gon-nexus** [comment]
The backend is not returning these fields, these are the ones that return:

![image](https://user-images.githubusercontent.com/73172087/120768535-8a00da80-c51c-11eb-8509-fe07af35fa1a.png)

@fjlopez  Can you add them?

**Comment by fjlopez** [comment]
I interpret that you requests additional fields in the view request response (`/api/tasks/3301?projection=view`), isn't? 

@gon-nexus can you confirm that you need: 
- for `Servei`: `serviceName` (label) and `serviceId` (id)
- for `Capa`: `cartographyName` (label) and `cartographyId` (id)

**Comment by fjlopez** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/108 fixes this need. @gon-nexus please, validate it.

**Comment by gon-nexus** [comment]
The new fields serviceName and cartographyName are correct, but we need a third field that is "layer", looking at Sitmun2 i think that is this field:
![image](https://user-images.githubusercontent.com/73172087/121513028-adc79300-c9ea-11eb-812c-ca082e805d29.png)

@fjlopez

**Comment by fjlopez** [comment]
The property *capa* contains a list of string separated by comma in SITMUN 2 that was stored in `STM_PARAMTTA` in the column `value`. 

In SITMUN 3, it should be `properties.layers` of type JSON array of string. 
```json
{
    "createdDate": "2014-09-22T10:02:06.000+00:00",
    "id": 31700,
    "name": "SIT.SIT_CAE1MV1_112L,SIT.SIT_CAE1MV1_123P",
    "order": null,
    "properties": {
        "layers": [
            "SIT.SIT_CAE1MV1_112L",
            "SIT.SIT_CAE1MV1_123P"
        ]
    }
}
```
*FME Extraction* synchronisation with STM2 has been implemented (see https://github.com/sitmun/sitmun-backend-core/issues/94)

**Comment by codinachssm** [comment]
Cartography column is still empty. And it's the sorting column.
Example, in sitmun2:
![image](https://user-images.githubusercontent.com/38311286/122032127-a2e87600-cdcf-11eb-8394-d386faa79888.png)

**Comment by gon-nexus** [comment]
To be able to add a cartography to the task, we need to modify the specification of the task, which is already sent to Unizar, however, there is no task with cartography in the test data, so no value appears, but when the modification is done, if you add a cartography to the task it will appear its name in the table

**Comment by fjlopez** [comment]
@codinachssm @gon-nexus https://github.com/sitmun/sitmun-backend-core/issues/110 adds the missing testing data

**Comment by fjlopez** [comment]
@codinachssm the requested data is now available
<image src="https://user-images.githubusercontent.com/3294927/122070438-42b8fa80-cdf6-11eb-8755-2fb94e3f9346.png" width="600"/>
