### ISSUE TITLE
CONNECTION - Tasks

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#48]
The Task panel in the Connection-Edit page should not be editable. In fact, it permits you to change the name of the task but when you Save changes there are not saved. It's only an informative panel.

**Comment by codinachssm** [comment]
And the column TASK TYPE is missing.

**Comment by gon-nexus** [comment]
Now the task panel is only informative, but to add the new column we need first the type projection on the task, , which is already requested to Unizar, when they implement it, we can do it

**Comment by fjlopez** [comment]
@gon-nexus done https://github.com/sitmun/sitmun-backend-core/issues/109
