### ISSUE TITLE
SERVICE - Edition

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#49]
When editing a service it permits you to choose any existing layer on the LAYER table to the grid. I think it should permit you to add a layer from the SERVICE you are editing, not from the complete LAYERS table. I'm not sure if it is a bug or if I don't understant the flow. If you add a layer from the list here and then you Save changes, it returns an "Internal error" message.

**Comment by codinachssm** [comment]
And the LAYERS column is missing in this grid.

**Comment by lucenasj** [comment]
This issues is the same to https://github.com/sitmun/sitmun-admin-app/issues/18, this function is in progress.

**Comment by codinachssm** [comment]
I get the error "undefined undefined" when I enter the Service Edition page. And the "Select the layers you want to register" panel appears empty, without any layers. Maybe the latest version is not loaded yet?

**Comment by codinachssm** [comment]
I still get the error "undefined undefined" and I cann't add any layer:
![image](https://user-images.githubusercontent.com/38311286/122174793-4fcffb00-ce83-11eb-8e44-39b781953785.png)

**Comment by lucenasj** [comment]
CORS ORIGIN ERROR #112

**Comment by lucenasj** [comment]
[https://github.com/sitmun/sitmun-backend-core/issues/112](url)

**Comment by lucenasj** [comment]
https://github.com/sitmun/sitmun-backend-core/issues/112

**Comment by codinachssm** [comment]
I get the same bevaviour: Error "undefined undefined" and the layers grid still empty.
I try with this WMS service: http://sitmun.diba.cat/wms/servlet/ACE1M
And I get this error: 
![image](https://user-images.githubusercontent.com/38311286/125068782-28e99b00-e0b6-11eb-86b1-58908e1f29f3.png)

**Comment by fjlopez** [comment]
I have reviewed this case. The admin transforms `https://sitmun.diba.cat/wms/servlet/ACE1M` into `https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities` which is an incomplete WMS GetCapabilities request. Most WMS servers are fine with this request but this service requires the standard parameter `service=WMS`.

@lucenasj, the fix is quick. Add `service=WMS` to the WMS requests, i.e.:

`https://sitmun.diba.cat/wms/servlet/ACE1M?service=WMS&request=GetCapabilities`

**Comment by lucenasj** [comment]
We have done this change, but not working.

This is har file
https://drivebox.nexusgeografics.com/f/f9dbbda087654f30935b/?dl=1

**Comment by fjlopez** [comment]
Your request requires to percent-encode the `&`.

Your request is `https://sitmun-backend-core.herokuapp.com/api/helpers/capabilities?url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities&service=WMS`. The query fragment of this URI is `url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities&service=WMS`. 

Servlet-based Java servers first splits by `&` and then the Spring Framework percent-decodes this query fragment. As `&` is not percent-encoded, the server process your request as:
```
url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities
service=WMS
```
and the remote request `https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities` fails.


If `&` is percent-encoded (`%26`) (i.e `url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities&service=WMS`), `&` is not present in the string:
```
url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities%26service=WMS
```
then the parameter value is percent-decoded:
```
url=https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities&service=WMS
```
and the remote request `https://sitmun.diba.cat/wms/servlet/ACE1M?request=GetCapabilities&service=WMS` returns the capabilities document.

**Comment by codinachssm** [comment]
After "Get data" I get this text in the Description:
![image](https://user-images.githubusercontent.com/38311286/125760124-2d5ae191-7953-4410-b2ad-5b960dd988fc.png)

Then, if I register some layers and I save changes, I get this error:
![image](https://user-images.githubusercontent.com/38311286/125760306-ab470450-41e0-479d-a3c7-6760d834e389.png)

If I correct the text in the Description ([object Object],[object Object]) and I change it to a valid text, then I can save again and it works OK.

But after saving the registered layers, when I go to one of these layers (LAYERS edit panel), I see that it automatically populated the Name and Description, but not the Layers field. I think this field should be automatically reported.

**Comment by codinachssm** [comment]
There is a mixed Catalan and Englsh text, I think:
![image](https://user-images.githubusercontent.com/38311286/125773128-6e133673-f24d-4753-8e9e-50554c55c10b.png)

**Comment by gon-nexus** [comment]
Fixes:
-Mixed translation: done.
-Add layers field to new layers: done
-Description bug: done, but one thing, the mistake was made because in the case of that service we were given the description in a different way than the others, so we have to add a way to return the data from this service, so if you see it happen again in some other service, please let me know!

**Comment by codinachssm** [comment]
I have a question: what will happen when we start having OGC API map services, will this part need to be reprogrammed?

**Comment by lucenasj** [comment]
It's not necessary  to be reprogrammed this part, because the XML response of getcapabilities request have same structure.

**Comment by codinachssm** [comment]
OK, thanks!
