### ISSUE TITLE
LLISTATS - DATA ALTA

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#5]
En alguns llistats (ex: serveis, territoris) permet filtrar per data d’alta, però no mostra aquesta columna. Potser cal una revisió d'aquest atribut a tots els llistats?

**Comment by lucenasj** [comment]
El problema són les dades que retorna el backend, sempre és null aquest atribut tant a servei com a territoris, si mirem el llistat d'aplicació si que mostra dates, perquè l'atribut està informat en aquest cas.

**Comment by codinachssm** [comment]
Ok, gràcies. Teòricament les dades haurien de ser les que tenim a Diba però anonimitzades, i la data d'alta hauria de venir informada.
@fjlopez puedes confirmar que en el conjunto de datos de prueba este valor está siempre a null en Servicios y Territorios? Más que nada para descartar un posible problema del API al devolver los datos. Gracias!
