### ISSUE TITLE
TERRITORY - TerType

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#50]
The TER_TYPID column is missing in the general Territories grid. It should be possible to search and sort by this field, so it is necessary to have it in the main grid (not only in the edit panel).

**Comment by codinachssm** [comment]
@gon-nexus Why did you move this issue to AdminApp F2?

**Comment by gon-nexus** [comment]
@codinachssm I wanted to put it on Pending Validation, thank you to tell me!
