### ISSUE TITLE
ROLE - Edition

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#51]
The TASKS panel should allow managing tasks at TASK LEVEL, not at GROUP LEVEL. In SITMUN2_adm the user can choose which subset of tasks (of a task group) a territory can access. Please see how it works in SITMUN2. You can see it in the images below.

**Comment by gon-nexus** [comment]
We need first the type projection on the task, , which is already requested to Unizar, when they implement it, we can do it

**Comment by fjlopez** [comment]
@gon-nexus done https://github.com/sitmun/sitmun-backend-core/issues/109
