### ISSUE TITLE
USER - Edition (pos_type missing)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#53]
The column POS_TYPE is missing in the User Position panel.

**Comment by codinachssm** [comment]
OK, but when editing this column, the possible values must come from a list of codes, the value must not be entered from text.
![image](https://user-images.githubusercontent.com/38311286/122176007-675bb380-ce84-11eb-9533-ae373c9c5358.png)

**Comment by fjlopez** [comment]
@codinachssm you're right, this is the user list `userPostion.type`. The only value of this list for testing is `RE`, but if you provide me with additional examples, I can add them to the test dataset.

**Comment by codinachssm** [comment]
I suppose each partner will be able to define its own code list table.
This is our proposal for DIBA (just to be able to have data to test):

CODE - DESCRIPTION
AJ – Ajuntament
AR – Ajuntament referent SITMUN
DB – Diba
DM – Demo
EM – Empresa
EN – Ens local (no ajuntament)
ER – Ens local (no ajuntament) referent SITMUN
EX – Externs
GN – Generalitat de Catalunya
PR – Projecte
TS – Test

Can you confirm that the code list table will be able to store the code and description?
Is it possible to show the description in this USer-Edit panel?

**Comment by fjlopez** [comment]
@codinachssm data added in English and Catalan to the code list `userPosition.type` (see https://github.com/sitmun/sitmun-backend-core/issues/113)
@lucenasj  the user edit panel should use this code list to address the above comment.
