### ISSUE TITLE
TASKS - Territory

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#54]
In the Territory Edit panel of all TASK Types (Download, Document,..) the TER_NAME column is missing. Only the TER_ID column exists.

**Comment by gon-nexus** [comment]
To be able to add the territoryName column we need to modify the specification of the task, which is already sent to Unizar, when they update the specification the new column will be there!

**Comment by fjlopez** [comment]
@gon-nexus done https://github.com/sitmun/sitmun-backend-core/issues/111
