### ISSUE TITLE
Review of Query Task

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#57]
**Purpose**: Identification of bugs related to the Query Task and increase the documentation available for the developers about the Task API. 

According to the data model:

| property | Type | STM model | storage STM3 | storage STM2 |
| --------- | ----------- | -- | -- | --  |
| `type`   | **uri** pointing to *TaskType* 5 | `Task.type` | `STM_TASK.TAS_TTASKID`|`STM_TAREA.TAR_CODTTA` |
| `name`   | string | `Task.name` | `STM_TASK.TAS_NAME` | `STM_TAREA.TAR_NOMBRE`|
| `group`   | **uri** pointing to a *TaskGroup`* | `Task.group` | `STM_TASK.TAS_GTASKID`| `STM_TAREA.TAR_CODGTA`|
| `connection` | **uri** pointing to a *DatabaseConnection`* | `Task.connection` | `STM_TASK.TAS_CONNID`| `STM_TAREA.TAR_CODCON`|
| `roles` | **uri-list** pointing to *Roles* | `Task.roles` | `STM_ROL_TSK.RTS_ROLEID` | `STM_ROLTAR.TAR_CODROL`|
| `availabilities` | **uri-list** pointing to *TaskAvailabilities* | `Task.availabilities` | `STM_AVAIL_TSK.ATS_TASKID` |`STM_DISPTAREA.DTA_CODTER` |
| `properties` | JSON Map | `Task.properties` (See note) | `STM_TASK.TAS_PARAMS` | |
| `properties.command` | string | | | `STM_CONSULTA.CNS_SELECT`|
| `properties.scope` | string | | |  `STM_CONSULTA.CNS_TIPO`|
| `properties.parameters` | JSON Array | | | |
| `properties.parameters[].type` | string | | | `STM_PARAMTTA.PTT_TIPO`|
| `properties.parameters[].key` | string | | |  `STM_PARAMTTA.PTT_NOMBRE`|
| `properties.parameters[].label` | string |  | | `STM_PARAMTTA.PTT_VALOR` |
| `properties.parameters[].value` | string |  | | `STM_PARAMTTA.PTT_VALOR` |
| `properties.parameters[].order` | integer |  | | `STM_PARAMTTA.PTT_ORDEN` |

*Note*: `properties` returns a JSON Map where `value`, `scope` and `parameters` are keys.

*Bugs* found in the task editor:

- [x] add new parameters form is broken
- [x] the input text are for SQL should be two columns wide
- [x] SQL is not stored, (in PUT requests, `property.command` is not set when `property.scope=SQL`)
- [x] Remove extra `_links` parameters in PUT requests 

*Bug fixed*

- [x] when type is SQL the new field shown is named  as `Etiqueta` (should be `Sentencia SQL` or similar)
- [x] `cartography` in POST/PUT should be a URI to the selected cartography and should be optional (see #46)
- [x] `type` in POST/PUT should be a URI to the selected cartography. 
- [x] `group` in POST/PUT should be a URI to the task type.
- [x] `properties` is null in POST/PUT when it should be a map with the properties `value`, `scope` and `parameters`
- [x] remove extra properties in the request
- [x] @fjlopez fix backend problem with `parameters` and other unexpected keys in `properties`.

## Expected API requests to /api/tasks

The following request are alternative. One of them is expected as POST request (see POST section [here](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.collection-resource)) for creating an entity and setting values which not are `uri-list` (`uri-list` follows [a different procedure](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.association-resource)). [PUT requests are similar](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.item-resource).

* full HTTP (asumes the server is at `localhost:8080`):
```json
{
"type":"http://localhost:8080/api/task-types/5",
"name":"sample",
"group": "http://localhost:8080/api/task-groups/11",
"connection": "http://localhost:8080/api/connections/2",
"properties": { "scope": "SQL", "command": "SELECT ...", "parameters": [] }
}
```
* relative URI:
```json
{
"type":"api/task-types/5",
"name":"sample",
"group": "api/task-groups/11",
"connection": "api/connections/2",
"properties": { "scope": "SQL", "command": "SELECT ...", "parameters": [] }
}
```
* slash+id (not recommended, see #56):
```json
{
"type":"/5",
"name":"sample",
"group": "/11",
"connection": "/2",
"properties": { "scope": "SQL", "command": "SELECT ...", "parameters": [] }
}
```

**Comment by lucenasj** [comment]
@fjlopez All unizar task have been developed?

**Comment by fjlopez** [comment]
Done, I updated the above bug list with an additional issue that I've found (Text in "Sentencia SQL" is not included in the PUT request) when I fixed the issue related to the backend.

**Comment by gon-nexus** [comment]
Hello! I was updating the query tasks screen to adapt it to the requirements and I encountered this error when I try to save the parameters ((if I don't have parameters, the request does not fail):

"message" : "Unrecognized field \"parameters\" (class org.sitmun.plugin.core.domain.QueryTask), not marked as ignorable (5 known properties: \"reportTask\", \"id\", \"scope\", \"command\", \"description\"])\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.sitmun.plugin.core.domain.QueryTask[\"parameters\"])"


I don't know if the error message is wrong, since I keep the parameters as in other task screens.
Here is the HAR:

[HAR_QUERY_TASKS_PARAMETERS_ERROR.zip](https://github.com/sitmun/sitmun-admin-app/files/6898877/HAR_QUERY_TASKS_PARAMETERS_ERROR.zip)

Thanks!!

**Comment by fjlopez** [comment]
@gon-nexus fixed. Check https://github.com/sitmun/sitmun-backend-core/issues/123 and close it
