### ISSUE TITLE
BOTONS Acceptar/Cancel·lar

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#6]
Fins ara els teníem en aquest ordre: esquerra Acceptar / dreta Cancel·lar. I en moltes altres aplicacions també estan així. Al nou Administrador estan al revés, tant a les finestres emergents de confirmació (per exemple, abans d'esborrar un element) com a la botonera superior esquerra (els 4 botons). És així per algun motiu?

**Comment by lucenasj** [comment]
No és per cap motiu, si voleu ho podem girar, no hi ha problema per això.
