### ISSUE TITLE
USER Edit - Permissions - Apply to children

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#65]
When adding a permission to a parent territory, the user can check the box "Apply to children". But where can one choose which functions are applied to the children?
The Save button does not save this checkbox. It is always unchecked.

**Comment by gon-nexus** [comment]
This checkbox must not be editable, it is already fixed, if you want to add roles to the child territories, when you add a new User Permission from user edit screen, if the territory's scope is regional, a dialog will appear to you to add child permissions, anyway, from the territory edit screen (if it has a regional scope), a child permission table appears, where you can do it directly.

**Comment by codinachssm** [comment]
OK. Just one more question: when you add a child-ter role to a user that already exists and already has the parent-ter role, you can't add this child role because the dialog doesnt activate. Can you? Maybe I'm not doing it the right way?

**Comment by fjlopez** [comment]
I am confused. I guess that you are discussing about:

<img width="240" alt="image004" src="https://user-images.githubusercontent.com/3294927/120824386-b0446b80-c558-11eb-8195-1e0607be1142.png">

"apply to children" is a property of User Configuration that means the role  _*implicitly*_ applies to the children of a territory, so you don't need to add these permissions explicitly. IMHO, this property should be editable.

**Comment by codinachssm** [comment]
Please confirm if I have understood correctly.
If the option "Applied to children" is checked, it means that this role applies only to the child territories.
If it is not checked, it means that this role applies only to the parent territory.
Is this the case?

**Comment by fjlopez** [comment]
To express it in other way, 

<img width="600" alt="image004" src="https://user-images.githubusercontent.com/3294927/120824386-b0446b80-c558-11eb-8195-1e0607be1142.png">

The user admin should interpret the above rows as follow:
- First row: This user will have the role 30 in the children of Provincia Barcelona
- Second row:  This user will have the role 17 in Sant Martí de Centelles
 
That is, the backend must ensure that this user will have the role 30 in all the municipalities of Provincia Barcelona but in Sant Martí de Centelles it will have the role 17 too.

**Comment by codinachssm** [comment]
OK thank you. It's clear now!
