### ISSUE TITLE
TERRITORY Edit - Error while saving (logo)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#67]
Even if you do not change anything in an existing territory, the following error message appears when saving changes:
<<Property: TerritorialAuthorityLogo Invalid vlaue;>>
There is no error message if you reomve the Logo filename value.

**Comment by lucenasj** [comment]
This error occurs because backend needs a url for the logo, and the default data is only the filename

**Comment by fjlopez** [comment]
I will update test data to match the spec. I keep open the issue meanwhile.

**Comment by fjlopez** [comment]
Fix in progress. Using as prefix for the URLs `http://sitmun.diba.cat/sitmun2/img/logo/`

**Comment by fjlopez** [comment]
Data fixed and UI tested. @codinachssm could you check this form? Do it ASAP as I plan to update the extent field today and this may be a breaking change for this form (@gon-nexus @lucenasj).

**Comment by codinachssm** [comment]
Tested. I confirm that it works correctly.
