### ISSUE TITLE
Dependabot alert is disabled

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-admin-app#68]
At https://github.com/sitmun/sitmun-admin-app/settings/security_analysis the following security measures are disabled: 

- [x] **Dependabot alerts** for receive alerts of new vulnerabilities that affect dependencies.
- [x] **Dependabot security updates**  for easily upgrade to non-vulnerable dependencies.
- [x] **Code scanning** for automatically detect common vulnerability and coding errors.

All of them are enabled at https://github.com/sitmun/sitmun-backend-core/settings/security_analysis

At least **Dependabot** should be enabled. Do you follow an alternative procedure for vulnerability checking?

**Comment by fjlopez** [comment]
@lucenasj this issue was in the `community` project due to an error; it belongs to `revisión interfaz`.

**Comment by lucenasj** [comment]
Can we close this issue?

**Comment by fjlopez** [comment]
Yep. I'll do.
