### ISSUE TITLE
TERRITORY - Permissions -Apply to children

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#69]
In Territory, when a territory can have children two permission list appear:

![image](https://user-images.githubusercontent.com/3294927/121510544-0a757e80-c9e8-11eb-8c2a-388a4556cc7b.png)

It should be a single list with a column "*aplica als fills*" similar to the permissions in the User form.

**Comment by fjlopez** [comment]
@lucenasj this issue was in the `community` project due to an error; it belongs to `revisión interfaz`.
