### ISSUE TITLE
Extract hardcoded login in Territory

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#70]
Ambit in *Territory* has this complex behaviour:

| Ambit | Effect |
| --- | --- |
| Municipality| Permisos, Territoris pares |
| Regional | Permisos, Permisos fils, Territoris fils |
| Total | Permisos | 

and *ambit* and *group tipus* are unrelated, so, for example. a `Mancomunitat` can be configured as `Total`. This may cause problems.

The proposal is as follows:
- Merge *ambit* and *grup tipus* in a new type named *tipus*.
- Add boolean properties to *tipus* to describe its behaviour (official, top, bottom)

| Top | Bottom| Effect |
| --- | --- | --- |
| true | true | `Permisos` (apply to children always false) |
| true | false | `Permisos`, `Territoris fils` |
| false | true | `Permisos` (apply to children always false), `Territoris pares` |
| false | false | `Permisos`, `Territoris pares`, `Territoris fils` |

**Comment by fjlopez** [comment]
@lucenasj this issue was in the `community` project due to an error; it belongs to `revisión interfaz`.

**Comment by IDEmenorca** [comment]
Help needed to validate this issue.  @fjlopez will you please review this?

**Comment by fjlopez** [comment]
The reference values are  defined in STM_TER_TYP

| TET_ID | TET_NAME | TET_OFFICIAL | TET_TOP | TET_BOTTOM | implies | verified |
|-|-|-|-|-|-|-|
|1|Àrea|true|false|false| Territoris fils and pares are shown | verified
|2|Consell Comarcal|true|false|false | Territoris fils and pares are shown | verified
|3|Consorci|true|false|false | Territoris fils and pares are shown | verified
|4|Mancomunitat|true|false|false | Territoris pares and fils are shown | verified
|5|Parc natural|true|false|true | Only Territoris pares are shown | verified
|6|Municipi|true|false|false | Territoris fils and pares are shown | verified
|7|EMD|true|false|true | Only Territoris pares are shown | verified
|8|Província|true|true|false | Only Territoris fils are shown | verified

@IDEmenorca the logic seems to be well implemented.

**Comment by fjlopez** [comment]
During the validation an issue has been found in https://sitmun.github.io/admin-app/#/territory
