### ISSUE TITLE
Descriptions translation panel

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#75]
The label is the same for each language: "Value"
![image](https://user-images.githubusercontent.com/38311286/122715418-20493600-d269-11eb-90dc-11a2111236be.png)

**Comment by codinachssm** [comment]
But how do I know which language each field refers to?
![image](https://user-images.githubusercontent.com/38311286/123080484-41eb1e80-d41d-11eb-8fc2-4622cc1af261.png)

**Comment by lucenasj** [comment]
![image](https://user-images.githubusercontent.com/72931574/123093838-71555780-d42c-11eb-8416-4765e1d356df.png)


Excuse me, we had a bug, which meant that the flags were not seen, now you can see.
