### ISSUE TITLE
LAYERS Edit - GEO_SOURCE is missing

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#76]
The column GEO_SOURCE (Grouping source) is missing.

**Comment by fjlopez** [comment]
@codinachssm could you describe the expected behaviour of such column in the UI? I remember that it has impact on updating multiple layers at once.

**Comment by codinachssm** [comment]
As you say, this attribute groups layers that come from the same cartography table and share the same attributes (Parameter configuration).
The goal is to facilitate applying changes to many layers at once (to all layers that have the same value to the GEO_SOURCE attribute).
A change in one of the layers of a GEO_SOURCE should ask if the change has to be propagated to the rest of the layers of the same GEO_SOURCE. A new layer should automatically take all attributes of the first layer having the same GEO_SOURCE. And if an existing layer is added to the GEO_SOURCE group, it should ask if it has to take the attributes of the first layer.

This feature is assigned to the MASSIVE ACTIONS functionality.
The missing field is a bug.

**Comment by gon-nexus** [comment]
Added "Source" to generic table column and form

**Comment by codinachssm** [comment]
Now I can assign a SOURCE to the layer, but:
- Can I manage the behaviour? I mean, when I assign a SOURCE to a layer, there's no dialog asking me if the system should apply the same config params as the original SOURCE.
- When I assign a SOURCE from the grid, not from the Edit panel, I cann't see the "Save" button, although it alerts me that if I navigate to another page I'll loose the changes. You can see this in the attached image:
- 
![image](https://user-images.githubusercontent.com/38311286/124568636-68f61700-de45-11eb-8d55-991024e8a6fb.png)

**Comment by codinachssm** [comment]
OK. But ithe translation of the new column title is missing. I see it in Englsh for all possible languages.
