### ISSUE TITLE
APPLICATION - Create (external)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#8]
When creating a new application I cannot enter its Title. And I cannot save the new app after entering Name, Type (external) and URL. Aren't these fields the only required?

**Comment by lucenasj** [comment]
on sitmun2 when edit a external Application, only Name, Url Desktop and Url Mobile can be edited

![image](https://user-images.githubusercontent.com/72931574/107372470-bb751680-6ae5-11eb-93fb-71e8baccd578.png)

**Comment by lucenasj** [comment]
fixed bug

**Comment by codinachssm** [comment]
Yes, you're right. Title should not be edited in external apps.
Is the fixed version uploaded? Can I test it?

**Comment by lucenasj** [comment]
> Yes, you're right. Title should not be edited in external apps.
> Is the fixed version uploaded? Can I test it?

yes

**Comment by codinachssm** [comment]
I created a new app by providing:
Name: prova
Type: external
Url: http://idebarcelona.diba.cat
When I click "Save" I get this error:
![image](https://user-images.githubusercontent.com/38311286/107491884-0cd7e100-6b8c-11eb-9736-4be7b850b418.png)

**Comment by lucenasj** [comment]
[sitmun.github.io.har.zip](https://github.com/sitmun/sitmun-admin-app/files/5957225/sitmun.github.io.har.zip)
@fjlopez
