### ISSUE TITLE
CONNECTION - Driver field (List of values)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#80]
Connection field should only be entered from the codelist, not from a free text (at grid and edit Connection panel).

**Comment by lucenasj** [comment]
The connection field cannot come by codeList, since the database connection host and the other data are dynamic, do you mean the driver field?

**Comment by fjlopez** [comment]
IMHO she refers to the driver. See https://github.com/sitmun/sitmun-backend-core/issues/119

**Comment by codinachssm** [comment]
Sorry!! I mean the Driver field!!
