### ISSUE TITLE
GENERAL - Labels in Grids

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#87]
Some labels include a number, which disappears when you click to sort the column.

![image](https://user-images.githubusercontent.com/38311286/133609610-524e1284-5ef9-400f-b3d5-8cbc350c3cff.png)

**Comment by gon-nexus** [comment]
These numbers appear when the table is sorted by more than one column (in this case by the columns you requested) and indicate the sort order of columns
If you want to check it manually, click the header of two columns while holding down the "shift" key, then the numbers will appear.

This function is automatically done by Ag-Grid
