### ISSUE TITLE
Layer form. Roles and Permission over the layer tab

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#95]
The tab 'Configuration of permissions on capes' must include a crosstab that contains the group of permissions and the role. In this way, the SITMUN administrator user will be able to immediately see the roles that have access to this layer. 

This functionality was described in the specification sheet of the contract...

**Comment by gon-nexus** [comment]
Waiting for https://github.com/sitmun/sitmun-backend-core/issues/124
